### ISSUE TITLE
Eliminate additional allocation in closure example

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#10]
Hi!  Really great proposal.  I had a look at it from the point of view of whether it's suitable as a target for a Scheme compiler, and generally, really good stuff.  I had a few thoughts and will file specific issues.

This issue relates to the closure example.  I think you probably agree that we should aim to have examples that are minimal, illustrative, and optimal.  That way they can be easy to understand while also illustrating that the proposal is capable of translating optimal examples.

In that regard I think we could revise the closure example to avoid the double allocation, basically putting the function pointer in with the data.  Keeping the same example:

```
function outer(x : f64) : float -> float {
  let a = x + 1
  function inner(y : float) {
    return y + a + x
  }
  return inner
}

function caller() {
  return outer(1)(2)
}
```

```
(type $clos-func-f64-f64 (func (param $env $clos-f64-f64) (param $y f64) (result f64)))
(type $clos-f64-f64 (struct (field $code (ref $clos-func-f64-f64)))
(type $inner-clos (struct (extend $clos-f46-f64) (field $x i32) (field $a i32))

(func $outer (param $x f64) (result (ref $clos-f64-f64))
  (ref_func $inner)
  (get_local $x)
  (f64.add (get_local $x) (f64.const 1))
  (new $clos-f64-f64)
)

(func $inner (param $clos (ref $clos-f64-f64)) (param $y f64) (result f64)
  (local $inner-clos (ref $inner-clos))
  (block $fail (result (ref $clos-f64-f64))
    (set_local $inner-clos (cast_down (ref $clos-f64-f64) (ref $inner-clos) $fail (get_local $clos)))
    (get_local $y)
    (get_field $inner-clos $a (get_local $inner-clos))
    (f64.add)
    (get_field $inner-clos $x (get_local $inner-clos))
    (f64.add)
    (return)
  )
  (unreachable)
)

(func $caller (result f64)
  (local $clos (ref $clos-f64-f64))
  (set_local $clos (call $outer (f64.const 1)))
  (call_ref
    (get-local $clos)
    (f64.const 2)
    (get_field $clos-f64-f64 $code (get_local $clos))
  )
)
```

Just as short as your example, just as illustrative, slightly more optimal I think -- besides avoiding the extra allocation, the down-cast in `$inner` is from a known reference type so you don't need the `intref` bailout.  Like your example, this closure representation strategy also allows for a group of mutually recursive closures with a single entry point to share a closure.  Of course there are many other possible representation strategies, and no one universal strategy; see http://www.andykeep.com/pubs/scheme-12a.pdf for an exhaustive look at representations even within the "display closure" strategy.  For this reason I think it's inappropriate for the WebAssembly spec to include closures; better to allow AOT compilers to choose their own representations.

**Comment by rossberg-chromium** [comment]
I agree that's nicer -- happy to accept a pull request. :)  (There is a `ref` missing in the param of the first type, btw. Also, I would probably name it `$code-f64-f64` for more clarity.)

One complication with this scheme is that it requires recursive function types, but that may be a good example to show them off. Also, I'm not sure how you would share environments between different inner functions, unless they happen to have the same signature? That's fine though.

**Comment by wingo** [comment]
Sure, will PR :)

Regarding environment sharing: in the language of that paper, it works with a clique of strongly-connected functions (functions whose free variables have the same lifetime).  If all functions are "well-known" (all callers of all functions are known), then the closure can just be a struct without a code pointer, of course, or even completely lambda-lifted.  But if only one function of the clique is not well-known, then the closure is a struct with the code pointer of that not-well-known function.  Section 2.3, case 1 of the paper.

**Comment by rossberg-chromium** [comment]
Well, IIUC, that works in a representation where the code pointers are untyped. But with the above, you could not share environments even among functions of the same clique, because their code fields have different types in general. You could make the code pointer an anyref, of course, but I'm not sure that's desirable.

**Comment by wingo** [comment]
The point is that if a function is are well-known, they it does't get called through the closure mechanism.  The closure is just another argument to a normal call. So a clique with only one function that's not well-known only needs the closure to call that not-well-known function, and all members of the clique receive the environment as their first argument as usual.

**Comment by rossberg-chromium** [comment]
We're probably talking about different things. Consider the following example:
```
func outer(a : i32, b : i32) : [i32 -> i32, (i32, i32) -> i32] {
    func inner1(x : i32) { return x + a + b }
    func inner2(x : i32, y : i32) { return x + y + a + b }
    return [inner1, inner2]
}
```
Under the encoding currently on the page, both inner functions can share the same closure environment. Under your merged scheme, I don't think that's still the case.

Not saying that it matters for the sake of example, but in practice it may. And when the variables in the closure environment are mutable (like in JS) then you need the sharing.

**Comment by wingo** [comment]
Hi!  Sure, we are talking about different things.  Using the strategy in your example, yes `inner1` and `inner2` can share the environment.  The strategy in my comment only allows for sharing for a set of functions with the same set of free variable lifetimes, with only one not-well-known member.  The set of {`inner1`,`inner2`} has the first property but not the second.

Incidentally, the Keep paper identifies "set of functions with same lifetime of free variables" with "clique of strong-connected functions"; the latter is only a subset of the former, as your example shows.  In that case the compiler could produce a different strategy; perhaps yours (probably optimal but some dereferencing overhead), or perhaps the one in mine (assuming that the generic safe-for-space strategy of display closures is a fine default and space-sharing is not as important in general).

Finally, note that display closures require assignment conversion, as noted by Cardelli in the 80's.  But most variables aren't mutable, and it's an easy property to determine statically, so it's not a terribly important point.

**Comment by wingo** [comment]
Ah, but I meant to say, getting back to the spec :)  I think all of this closure-representation noodling should be in the domain of the compiler targetting WebAssembly, and not the WebAssembly implementation.  Just MHO tho!

**Comment by binji** [comment]
It seems like this issue was addressed, as the fix was merged and there hasn't been any discussion for 3 years. Feel free to reopen if there are unaddressed concerns.
