### ISSUE TITLE
Agenda for subgroup meeting - July 28, 2020

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#103]
The next subgroup meeting is **July 28, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

* Wasm interop with host languages like JavaScript (@tebbi)

**Comment by tebbi** [comment]
I could present some ideas on how Wasm interop with a host language like JavaScript could look like. The basic idea is to embed information in RTTs on how a type looks like to the host language.

**Comment by binji** [comment]
Notes are up here: https://github.com/WebAssembly/meetings/blob/master/gc/2020/GC-07-28.md.
