### ISSUE TITLE
Weak maps for GC references?

### ISSUE THREAD

**Issue by skuzmich** [WebAssembly/gc#106]
Would browser VM be able to support weak maps for GC references without additional overhead?

Some languages provide an identity hash code for every object, usually a i32 random number that is always the same for a particular object instance.

These identity hash codes are often computed lazily because many objects never need them. They either never put into a hash table or hash code method is overridden to not depend on object identity. In case VMs already have internal hash codes (I assume they would not want to provide them to user-space directly) and could support weak maps efficiently, languages would be able allocate their identity hashCodes lazily inside these weak maps, saving 32 bits for most GC objects.

**Comment by titzer** [comment]
JavaScript has [WeakMap](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap), which was designed specifically for this purpose. It should be fairly easy to use in the JavaScript embedding. Of course that doesn't help other embeddings, so the question is whether Wasm should have similar functionality.

**Comment by brion** [comment]
A WeakMap equivalent would be great for mapping publicly exportable object references to local pointers without exposing the pointers to forgery by calling modules.

**Comment by tlively** [comment]
We have consensus on a JS interop solution (https://github.com/WebAssembly/gc/issues/279) that does include WeakMap support, although it does come with some space overhead in the V8 implementation. Language implementations could use this to avoid allocating additional space in their objects as OP suggested.
