### ISSUE TITLE
Agenda for subgroup meeting - August 25, 2020

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#115]
The next subgroup meeting is **August 25, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

* High-level summary of research into low-level GCs (Ross Tate)

**Comment by RossTate** [comment]
I would like to present a high-level summary of the history of research related to the challenges were are facing in this proposal. I think it would be helpful for understanding why these challenges are more difficult than they appear to be, and I think it is generally useful to be informed of the techniques that enabled others to overcome similar challenges and make major advances towards similar goals.

**Comment by binji** [comment]
Sounds good, I think we could spend the whole time talking about this, so let's add a timebox only if/when we get any other agenda items.

**Comment by RossTate** [comment]
Cool. I've now put together slides with this plan in mind.

**Comment by binji** [comment]
Thanks again for the meeting everyone! Notes can be found here: https://github.com/WebAssembly/meetings/blob/master/gc/2020/GC-08-25.md
