### ISSUE TITLE
Clarify type grammar for arrays

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#12]
I am not entirely sure, but it would seem that the spec does not allow arrays of refs, or of types that include refs.  The type grammar says:

```
num_type       ::=  i32 | i64 | f32 | f64
ref_type       ::=  (ref <def_type>) | intref | anyref | anyfunc
value_type     ::=  <num_type> | <ref_type>

packed_type    ::=  i8 | i16
storage_type   ::=  <value_type> | <packed_type>
field_type     ::=  <storage_type> | (mut <storage_type>)

data_type      ::=  (struct <field_type>*) | (array <fixfield_type>)
func_type      ::=  (func <value_type>* <value_type>*)
def_type       ::=  <data_type> | <func_type>
```

But `fixfield_type` is not defined.  Can you clarify?

Wanting an array of refs seems like a normal thing to want.  If this is not in-scope for the current spec, the spec should include some words about this.

**Comment by rossberg-chromium** [comment]
That was a left-over from an older grammar, should be `field_type`. Fixed.
