### ISSUE TITLE
Prototyping the SOIL initiative proposal: call for volunteers

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#123]
There is a lot of community enthusiasm for the GC proposal right now. @dcodeIO is working on a prototype in [Binaryen](https://github.com/webassembly/binaryen) and @brion has expressed interest in using that prototype to investigate JS compilation once it is ready.

I'm hoping we can harness some of that energy to work on prototyping the [SOIL initiative proposal](https://github.com/soil-initiative/gc/pull/1) as well. Getting concrete experience with both of these designs is going to be hugely impactful for driving GC forward, no matter what the final GC proposal looks like.

If you're interested in helping out, I would be happy to help shepherd your prototyping work in Binaryen by discussing the implementation design with you and providing code review. I'm happy to discuss details with you here or on the [WebAssembly Discord](https://discord.gg/b2SPecS).

Please also let me know if you would be interested in investigating compiling your language to a prototype of the SOIL initiative proposal. We can work with @RossTate to figure out which features of the proposal your language will need and prioritize prototyping those features.

@dcodeIO, would the AssemblyScript project be interested in investigating the SOIL initiative proposal as well? If so, @torch2424, I'm sure you have a lot on your plate, but would this be something you would be interested in working on? @RossTate, do you know anyone who would be interested in working on an implementation of the proposal?

**Comment by tlively** [comment]
If someone is interested in prototyping the two-types solution (which would definitely be less work) in Binaryen, I would be happy to shepherd that work as well!

**Comment by brion** [comment]
I'm reading the SOIL proposal and it looks like the 'explicit' type relationships would allow for an optimized implementation to generate a NaN-boxing scheme for the universal value representation for my JS compiler design, while potentially falling back to heap boxing on a simpler engine. Interesting... will try a new sketch of that on top of this plan, see what it looks like...

**Comment by brion** [comment]
Ok definitely not nan-boxing, but neatly letting the engine optimize "boxed" i32s into pointer tags magically sounds nice! But not being able to predict the performance of them is potentially not great. Overall though it's quite interesting. Most of my internals objects will be similiar under this design, but with some arrays combined into the structs for Strings and BigInts and such. Might be able to replace the type_id field with just using the RTT with a switch_case etc when needed for dispatch.

**Comment by torch2424** [comment]
@tlively Thanks for reaching out! :smile: 

> I'm sure you have a lot on your plate

Definitely do haha! :joy: But totally down to help with this as I can, as I know it's going to be an important part of AS (And both my work and personal goals align with helping that!)

> , but would this be something you would be interested in working on?

Totally! :smile: Though, I'm not entirely sure how I could help? You and @dcodeIO Let me know how/if I can! For now though, I'll let @dcodeIO drive this from the AS. As they have been following this much more closely than me :smile: 

---

Thanks! :smile: :+1:

**Comment by binji** [comment]
IMO, the first thing to do for either the SOIL or two-types proposals is to write up a first-pass binary and text format. It'll be hard to prototype anything without that.

**Comment by tlively** [comment]
Right, concretely what we need to happen is:

 1. Work with proposal authors (@RossTate for the SOIL proposal or @taralx for the two-type proposal) to define complete instruction sets and text formats.

 2. Implement parsing, printing, and interpretation for the types and instructions in Binaryen.

 3. After that, @dcodeIO, @brion, and anyone else can experiment with lowering source languages to the GC proposals.

So I am mostly looking for help with (2).

**Comment by ajklein** [comment]
Wouldn't you also want a runtime/engine interested in prototyping? It's unclear to me how much value would be gained from a toolchain alone.

**Comment by tlively** [comment]
That would certainly be useful, but I can't personally be as helpful with that as I can with Binaryen work. Even with just a debugging interpreter rather than an optimizing engine implementation, we would still be able to comparatively evaluate 1) how easy it is to emit GC code, 2) code size, and 3) how many casts or other performance-sensitive operations real-world code executes. Having a toolchain prototype also makes an engine prototype much more valuable, which makes it more likely that someone will work on one.

**Comment by MaxGraey** [comment]
Also I'm wondering is it possible polyfill GC on Binaryen side? So even without support GC from runtime engine we could use GC

**Comment by tlively** [comment]
@MaxGraey yes, in principle that would be possible, but it would be a large project on its own so it probably doesn't make sense to focus on for now.
