### ISSUE TITLE
Agenda for subgroup meeting - September 8, 2020

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#126]
The next subgroup meeting is **Spetember 8, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

* Discussion: Follow-up Q/A on low-level GC research presentation (@RossTate) [10 minutes]
* Discussion: Resource Limits  #122, #35 (@brion) [10 minutes]
* Discussion: Requirements  #121 (@fgmccabe) [40 minutes]

**Comment by RossTate** [comment]
I think we should discuss #119. It provides a simple approach to addressing many of the standing problems. It also serves as a good follow-on to last meeting's presentation because it executes upon the some of the takeaways from the presentation.

**Comment by rossberg** [comment]
Just a heads-up that I will be off the grid for the next two weeks, so won't be able to attend the next meeting.

**Comment by RossTate** [comment]
Oh okay, then I think it would be poor form to discuss #119. Given that, since we didn't have time for Q&A and discussion of last meeting's presentation, maybe setting aside some time for that would be useful for the group.

**Comment by binji** [comment]
> Given that, since we didn't have time for Q&A and discussion of last meeting's presentation, maybe setting aside some time for that would be useful for the group.

That sounds OK to me, though I'm not sure we'll fill an hour with discussion on this topic, and I'd like to avoid holding a meeting that only has enough content for a half-hour or less. Perhaps we can defer the discussion to the next meeting unless we get another agenda topic?

**Comment by RossTate** [comment]
Sounds like a good plan to me. I agree that we shouldn't plan for an hour of discussion. Half an hour is the most I would expect, and I'm not sure even that. So it makes sense to schedule based on what other agenda items come up, if any.

**Comment by brion** [comment]
It may be too early to have a discussion on it but I'd love as a potential language implementor to have a better understanding of potential behavior on allocation failure cases with respect to heap or object size limits (#122).

**Comment by fgmccabe** [comment]
I would like to put the requirements on the agenda. There will have been enough time by then for people to have read the proposed doc.

**Comment by RossTate** [comment]
I'm happy to have Q&A time be brief to make more room for other items. If we put it first and it ends early, then that'd give even more time.

**Comment by binji** [comment]
OK, I've added these to the agenda. @brion @fgmccabe @RossTate can you give timebox estimates for these discussions?

**Comment by brion** [comment]
Limits & failure cases is probably pretty short if there's general agreement on how to proceed with failing allocations for the MVP. Does 10-ish minutes sound reasonable? I imagine if there are questions we can't resolve quickly with general agreement they'll be pushed back for later offline discussion.

**Comment by RossTate** [comment]
I imagine the requirements discussion will benefit from a lot of time, so I would put my discussion down for just 10 minutes. I would even suggest putting it before the requirements discussion so that, if it turns out that many have the questions have already been answered through offline discussions, then we can hand off the resulting extra time to the requirements discussion.

**Comment by Dima00782** [comment]
Hi, I want to attend these meeting and I filled up the form but haven't got any invitation yet.
cc: @littledan

**Comment by brion** [comment]
I also submitted the form a few days ago and haven't received an invite.

**Comment by binji** [comment]
Sorry about that, I've added you to the meeting. Let me know if you don't get the email.

**Comment by brion** [comment]
Thanks, got it! :)

**Comment by binji** [comment]
Notes for meeting here: https://github.com/WebAssembly/meetings/pull/635

Thanks, everyone!
