### ISSUE TITLE
Clarification request on RTTs

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/gc#127]
Take the following simple class hierarchy (say in Java):
```
class Super {}
class Sub1 extends Super {}
class Sub2 extends Super {}
```

@rossberg For the current MVP, do you expect instances of `Sub1` and `Sub2` to have the same RTT or different RTTs? What about for a Post-MVP?

**Comment by rossberg** [comment]
There should be a way to create distinguished RTTs, see the TODO [here](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#runtime-types-1).

**Comment by RossTate** [comment]
Thanks for the clarification and the fast response! That's what I expected, but I wanted to check given that TODO has been open for a while.
