### ISSUE TITLE
Agenda for subgroup meeting - September 22, 2020

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#133]
The next subgroup meeting is **Spetember 22, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

[Incorporate RTTs into the type](https://github.com/WebAssembly/gc/issues/119) (Ross Tate) [20 min presentation, 20 min discussion]

**Comment by RossTate** [comment]
I would like to discuss #119. It seems to be a relatively simple change to the existing proposal that would address many of the standing issues, and it is in line with the some of the takeaways from the presentation I gave on related work on typed assembly languages.

**Comment by binji** [comment]
Sounds good, how much time should we allot?

**Comment by RossTate** [comment]
Hmm, maybe 20 minutes for presentation and 20 minutes for discussion? I may be overestimating presentation time and underestimating discussion time though.

**Comment by conrad-watt** [comment]
@binji would it be possible to get a calendar invite? I signed up through the form a little while ago.

**Comment by binji** [comment]
@conrad-watt you should have an email now. Sorry about that, I didn't have the form set up to send me email updates apparently. :-/

**Comment by binji** [comment]
Notes here: https://github.com/WebAssembly/meetings/pull/649. Thanks everyone!
