### ISSUE TITLE
Mysterious disappearance of `struct.new` in MVP.md

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#135]
It appears that `struct.new` and `array.new` disappeared in a https://github.com/WebAssembly/gc/commit/20a80e34f46e4f68d0ff2dccec78e95a3f4fb267, without much explanation.

I am not sure if this was a typo or if the intention that they be folded together with the RTT variants of those instructions. I couldn't find an issue describing any rationale why that happened.

**Comment by jakobkummerow** [comment]
Yes, they have disappeared, in favor of the respective `_with_rtt` variant. A planned follow-up is to drop the `_with_rtt` suffix (now that it is no longer needed for distinguishing purposes).

IIRC, the primary reason was the insight that most struct/array allocations would probably want to manually specify their RTT anyways (to allow non-trivial casting of the created objects), making the RTT-less `struct.new` nearly useless.

**Comment by titzer** [comment]
Was there some reason to not just drop the `_with_rtt` suffix and change the default behavior then? The opcode space now has a hole in it, which presumably would be filled by renumbering again.

I find it confusing that bytecodes appear and disappear but numberings stay the same...is there some kind of subtle binary format compatibility dance going on between different tools? It makes it hard to track what the source of truth for this proposal is, especially since there is no reference interpreter implementation or test cases.

**Comment by Horcrux7** [comment]
> A planned follow-up is to drop the _with_rtt suffix

Is there a schedule for this? If there is a short timeline I can save myself having to rename it.

**Comment by rossberg** [comment]
@titzer, the only reason is that there might still be value in reintroducing the RTT-less form later, but it is not crucial for the MVP, so got cut.

@Horcrux7, a possible name change should be your smallest concern wrt to stability of the proposal at this stage. ;)

**Comment by tlively** [comment]
There might be some value in discussing what threshold of publicity and consensus we expect changes to reach before they are committed, but I'll close this particular issue because the original question has been answered.
