### ISSUE TITLE
Will the restriction about global initializers be lifted?

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/gc#140]
Hello,
currently, global initializers cannot refer to locally defined globals. However, the first code block [here](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#runtime-types) implies that this restriction will be lifted or relaxed. Is it safe to assume that global initializers will be able to refer to already defined local globals?

**Comment by rossberg** [comment]
Ah, yes, good point. It probably should, so that they can at least be used sequentially. I think that would be good for other use cases as well, which are completely unrelated to GC.
