### ISSUE TITLE
Interoperability of array types with host

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#146]
How would the interoperability of array types with the host (JavaScript) work? For example I have define an i8 array and an import like:
```
(type $bytes (array (field i8)))
(import "foo" "bar" (func $bar(param $val (ref null $bytes))))
```

If I call this function, can I expect a Uint8Array in JavaScript and a byte pointer in another host?

If so, shouldn't we then predefine these primitive arrays as own type and add the type mapping to the proposal?

Or is this only possible via interface types? What will I receive without such interface type definition?

**Comment by fgmccabe** [comment]
This is not going to work at all without support from some glue code. There is not enough information in the signature. Apart from anything else, the $bytes parameter is (as far as wasm is concerned) an index not an address.

**Comment by Horcrux7** [comment]
> This is not going to work at all without support from some glue code.

How should this glue code look? Both already the simplest array types.

> the $bytes parameter is (as far as wasm is concerned) an index not an address.

$bytes is a type. If I call the function then I pass a real reference. And a reference is a address. I does not understand what you means.

**Comment by tschneidereit** [comment]
@rossberg's proposal has an accompanying proposal on the JS side which lays out how this reflection would work. See [this explainer](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP-JS.md) by @lukewagner for how the two interact, and [my Typed Objects explainer](https://github.com/tschneidereit/proposal-typed-objects/blob/master/explainer.md).

Note that both of these are somewhat outdated by now, but AFAICT the fundamentals haven't changed enough to make these explainers lose all meaning :)

**Comment by tlively** [comment]
There's slightly more discussion on arrays in #151, so I'll close this similar issue.
