### ISSUE TITLE
Agenda for subgroup meeting - October 20, 2020

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#147]
The next subgroup meeting is **October 20, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

None yet.

**Comment by rossberg** [comment]
Yes, will do.
