### ISSUE TITLE
Clarify equality on `intref`

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#15]
Considering this proposal from a Scheme point of view, I was asking myself how to implement efficient integers, and was happy to see the `intref` section of the proposal.  I think it's the right thing to include, with the one caveat that it will force every down-cast from anyref have to check whether the ref is an immediate or not.  That's a bit sad, but oh well.

Anyway, enough with the preface :)  I think the spec is missing a specification of `same` on intrefs.  The whole point is to allow for immediates, and immediates aren't distinguishable!  I think you have three options: one, no intref is the `same` of any other; two, intrefs are compared by value, not by identity; and three, use object identity, effectively exposing which intrefs are immediates and which are heap values.  Incidentally this would allow a program to know what the fixnum limit is.  Since `same` has to work on `anyref`, I think that rules out the first option; and implementing the second option would add general complication to the `same` path.  So I think I'd go with the third option.

**Comment by rossberg-chromium** [comment]
I was assuming option 2, though in the light of your other question #11, option 2 might be the better choice. Option 3 is a no-no, since it would introduce implementation-dependent behaviour.

Why do you think that option 1 is ruled out by `anyref`? If you can implement option 2 then you can certainly implement option 1.

**Comment by wingo** [comment]
I think regarding option 1, I was thinking of trying to rule out `same` on intrefs via the type system.  It's certainly possible to do (1) dynamically, but then you break `(same x x)`, which can be false only for intrefs (?).  Compare-by-value (option 2) certainly seems better in that regard, but then you lose (?) the ability to completely inline 

I suspect (but obviously this is just speculation) that some form of option (3) might come about in practice; if a WebAssembly compiler wants to know the barrier between immediates and fixnums, they will be able to measure that by timing.  But I get your point and it having implementation-independent semantics sounds like a good goal.

**Comment by rossberg-chromium** [comment]
Oh, the right way to do (1) is to make all values equal, not different (which is somewhat natural from a type-theoretic perspective, where all values are indistinguishable at top type). Otherwise you indeed break the equivalence relation properties of the instruction.
