### ISSUE TITLE
`this` arg for methods in JS API

### ISSUE THREAD

**Issue by brion** [WebAssembly/gc#153]
In light of recent discussions about JS interop over on #150 I revisited the [MVP-JS.md](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP-JS.md) document.

A common scenario for JS APIs is to pass objects around that have both readable and sometimes writable properties and callable methods; I believe this *must* be supported also on the "JS typed object" views of GC structs for the goal of code migration to be achieved.

However, while it is apparently possible to attach a prototype object with function reference properties on it when creating a struct type from JavaScript and importing it into Wasm, I don't understand how the methods are supposed to pass a `this` parameter with the target object unless the method functions are also written in JavaScript.

This would seem to mean that to create an interoperable struct type you must:
* write a JavaScript module as well as a Wasm module
* create a prototype object in JavaScript with regular JavaScript functions that forward to the module's Wasm functions while currying the `this` argument into the regular arguments
* resolve the circular dependency between importing a type with functions that reference exported functions that haven't been exported yet at import time -- perhaps by modifying the prototype after instantiating the module, but before calling any code in it

I'm wondering if there might be a way to apply Wasm functions directly to a prototype without an intermediary JavaScript function or if that's considered an unavoidable limitation of this proposal.

**Comment by fgmccabe** [comment]
The Interface Types proposal will have a method (sic) for doing this.

**Comment by brion** [comment]
Where can I see the docs for this? I don't remember seeing it in the proposal.

**Comment by brion** [comment]
@fgmccabe are you thinking of this discussion? https://github.com/WebAssembly/interface-types/issues/87 It seems incomplete and undecided so far.

**Comment by brion** [comment]
Also just want to check if IT is a required dependency for GC to reach its goals, or if they're meant to be separate specs which can be implemented independently?

**Comment by tlively** [comment]
We have consensus to have "no-frills" JS interop (https://github.com/WebAssembly/gc/issues/279) in the MVP, so there won't be any way to install custom prototypes on GC objects. Exported accessor functions will be the only way to inspect or modify WasmGC objects from JS. PRs adding ideas for richer interop to the [post-MVP doc](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Post-MVP.md) would be very welcome, though.
