### ISSUE TITLE
Agenda for subgroup meeting - November 3, 2020

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#157]
The next subgroup meeting is **November 3, 2020 at 9am PDT (6pm CET)**. As with other Wasm meetings, we'll host this on zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

Agenda:

None yet.

**Comment by titzer** [comment]
I'd like to give a presentation about what I've been doing for the past half year, but I won't be ready for the November 3rd meeting, so I'd like to propose it for the November 17th meeting. I might need a full hour for the presentation and discussion.

**Comment by conrad-watt** [comment]
With no agenda set currently, will we skip this meeting?

**Comment by rossberg** [comment]
I wouldn't mind, many people probably have their minds elsewhere today anyway.

**Comment by binji** [comment]
Sounds good, I'll cancel.
