### ISSUE TITLE
Agenda for subgroup meeting - November 17, 2020

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#159]
Since no one posted an issue for the agenda yet, I'll start one here.

**Comment by titzer** [comment]
I propose to discuss layered runtime systems, in particular the work I have been doing to build a functioning JVM on top of Wasm. Bonus: a student of mine used the same technique to make Python work!

I'll post a document and a link to slides soon.

**Comment by titzer** [comment]
@binji @tlively Could someone update the agenda?

**Comment by binji** [comment]
AFAIK there's no official agenda doc, we usually just use an issue like this. Seems OK to use this one for the meeting tomorrow. Thanks for adding!

**Comment by titzer** [comment]
Could you add an item in https://github.com/WebAssembly/meetings/tree/master/gc/2020 ?

**Comment by binji** [comment]
Sure: https://github.com/WebAssembly/meetings/pull/675

But usually for GC subgroup meetings these are added after the fact.

**Comment by titzer** [comment]
Ok. Here is a link to my slides:

https://docs.google.com/presentation/d/1HaxcyHoKle79koLfqhpLKil24w_98GXZGwsZFJo-qxE/edit?usp=sharing

**Comment by titzer** [comment]
And here's a link to a longer document that discusses Jawa in detail.

https://docs.google.com/document/d/14T8RPgQKztURiHmzyP_Ju2S9nrIZWDaAb8eSx3NiiYw/edit?usp=sharing

**Comment by tlively** [comment]
Thanks everyone, and sorry for the Zoom issues. The notes PR is https://github.com/WebAssembly/meetings/pull/676.
