### ISSUE TITLE
Can a field be an embedded value?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#163]
The [type grammer](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#type-grammar) says a field of an array or a struct is a storage type, which is a value type (ignoring packed types), which is either a number like i32, or a reference type.

However, the examples on the same page have this:
```wat
(type $vector (array (mut f64)))
(type $matrix (array (type $vector)))
```

Is a matrix an array of *references* to vectors, or an array of vector *values*?

Is "type" a typo for "ref" perhaps in that example? Or is it an alias for "ref"? Or do we actually intend to allow embedded values like e.g. Go does?

(If we allow embedded values, then the Binaryen type system for fields is insufficient, as it cannot represent them, which is why I ran into this. cc @tlively @dcodeio)

**Comment by jakobkummerow** [comment]
Probably a typo for `(mut (ref $vector))`. We definitely don't support embedded objects currently. (It's on the post-MVP list to look into that; we'll probably want _some_ form of it eventually, but the details are an open question.)

**Comment by kripken** [comment]
Thanks @jakobkummerow ! I opened a PR to fix the typo now.

Should it be `mut`? Seems more natural for the references to be immutable, but I may be missing something.

**Comment by jakobkummerow** [comment]
In the MVP, arrays only support mutable elements. See https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#type-definitions.

**Comment by kripken** [comment]
Oh, interesting... the text also has
```wat
(type $buf (array i8))
```
so seems like that's a mistake too? I'll add it to my PR.

**Comment by rossberg** [comment]
What @jakobkummerow said. Specifically, see [here](Post-MVP.md#nested-data-structures) for a sketch of the extension that would allow direct nesting of aggregates, as in C. The main reason for leaving it out of the MVP is that it requires introducing inner references in some form or another. It also allows the shape (interleavings of boxed and unboxed slots) of a heap value to become arbitrarily complex, so a typical GC will need type-like object descriptors to make them scale efficiently.
