### ISSUE TITLE
Intref specification incomplete without reference to overflow

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#17]
I think the intref section probably needs some example code for how to implement addition over arbitrary-precision integers in order to make sure it covers its use case.  For that we would need to reference something like https://github.com/WebAssembly/design/blob/master/FutureFeatures.md#integer-overflow-detection.  Is there a newer draft for that?

**Comment by rossberg-chromium** [comment]
Good idea. There is an issue on the design repo for arithmetics with carry (WebAssembly/design#1021), but it depends on multi values, since the respective instructions want to return two results. It wouldn't harm to sketch something anyway. Please feel free to create a PR :).

**Comment by wingo** [comment]
Cool.  I regrettably don't have the time to do a good job here at the moment, but just wanted to note that at some point "work should be done" (passive voice, heh heh) before nailing down intref details.

Alternately if the semantics really is 32-bit integers, then the features are orthogonal; adding two intrefs can return an anyref (or a intref + `(ref $bignum)` variant), the overflow happens just on the `i32` operations and not the tagging or untagging...

Alternately alternately, and just musing here -- were you thinking that the `tag` operation could simply branch if the number is out of range?  That would be an elegant solution to both this issue and #16.

**Comment by rossberg-chromium** [comment]
Agreed. I added your suggestion of providing a branching `tag` instruction.
