### ISSUE TITLE
Text syntax for array type definition

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#172]
What ist the correct syntax for an array type definition in the text format?

**SpiderMonkey WasmTextToBinary** function which come from the wasm-tools https://github.com/bytecodealliance/wasm-tools
use the follow syntax
```
(module
  (type $bytes (array i8))
)
```

**wasp wat2wasm** https://github.com/WebAssembly/wasp
use this incompatible syntax
```
(module
  (type $bytes (array
    (field (mut i8))
  ))
)
```

Which is the right syntax? Because only one field is possible in the binary format that I would prefer the syntax from SpiderMonkey.

**Comment by rossberg** [comment]
Should be the former. Fields occur in structs only.

**Comment by jakobkummerow** [comment]
But `mut` should be explicit, right? Because we may eventually figure out how to support non-`mut` arrays...

```
(module
  (type $bytes (array (mut i8)))
)
```

**Comment by rossberg** [comment]
Ah, yes, you're correct.
