### ISSUE TITLE
Binary format of br_on_cast

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#173]
I am having trouble implementing it. I see [the prototype doc](https://docs.google.com/document/d/1DklC3qVuOdLHSXB5UXghM_syCh-4cMinQ50ICiXnK3Q/edit?pli=1#) says it has 3 immediates, the index of the block it targets, and two heap types. Given this:
```wat
(br_on_cast $out $B (ref.null $A) (rtt.canon $B))
```
Binaryen will emit this:
```
fb 42 00 02 00
```
`fb` is the GC prefix, `42` is the code for `br_on_cast`, and then the immediates come: `00` for the block target (it targets the block it is immediately in), then `02` for the first heap type, and then `00` for the second heap type it is trying to cast it to. But this last immediate errors in wasp with `Unknown reference type: 0` and in v8 with `block type index 0 is not a signature definition`.

Should there be something else than a heap type for that immediate?

**Comment by jakobkummerow** [comment]
See the comments on the prototype doc: we have implemented `br_on_cast` without the heap type immediates that the spec document currently demands.

The background is the discussion around dropping these immediates that can be deduced from the operand stack. In the interest of module binary size, it would be advantageous to drop them; however there were some concerns that super-simple interpreter-only implementations might benefit from having them. (Personally I think that module size for all eternity is a far stronger argument than implementation effort for super-simple (=early?) implementations; objectively speaking, the question hasn't been settled yet.) See https://github.com/WebAssembly/function-references/pull/31
So in V8 we have implemented some instructions with and some without type immediates. You can see that (unfavorably) as chaos, or (favorably) as proof that both approaches are implementable :-)

**Comment by kripken** [comment]
I see, thanks @jakobkummerow ! I missed the comments and notes, sorry about that...
