### ISSUE TITLE
RTT default values

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#175]
Do RTTs have default values? I can't find an answer in the docs, but maybe I missed it.

Seems like the default could be `rtt.canon` of that type. That's what I assumed in binaryen so far.

**Comment by jakobkummerow** [comment]
My understanding is that RTTs are not defaultable, and that's one of the reasons why the `let` instruction is in this proposal -- can't use regular locals for RTTs.

Specifying `rtt.canon` to be the default might work, except when you want the RTT depth to be part of the static type.

**Comment by rossberg** [comment]
As @jakobkummerow, they are not defaultable, similar to typed references.

**Comment by kripken** [comment]
I see, thanks. I'll update the binaryen implementation then.
