### ISSUE TITLE
Rtt depth for allocation operations

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/gc#186]
Hello,
currently, `{struct, array}.new_*` operations take as argument an rtt with defined depth. Is this necessary or can this requirement be relaxed?

**Comment by RossTate** [comment]
I imagine it could be relaxed, but I'm curious what the use case is in this MVP where you know the `rtt`s exact type but not its depth.

**Comment by tlively** [comment]
Closing this, but feel free to reopen if it merits further discussion.
