### ISSUE TITLE
Include mention of possible varargs+ref calling convention?

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#19]
In Scheme, Lua, Python, and so on, values and functions don't have types at compile time, and so the normal, general calling convention is just "Here are N values, have at it".  A common way of implementing this would be to pass up to 6 arguments in GPRs, the rest on the stack, with one GPR reserved for the number of arguments.  Each function checks the `nargs` register in its prelude to assert that it's called with the right number of arguments.  Functions can also branch on `nargs` to implement multiple-arity dispatch.

In WebAssembly of course we would like to be able to provide an efficient compilation target, but I don't know if that's possible here.  If I had to implement Lua or Scheme's call/return convention, I would use an explicit per-thread stack, and make each function be of type

```
(type $lua-func (func (param $thr (ref $thread)) (param nargs i32) (result i32)))
```

Here the result indicates the number of returned values that the function pushed on the stack.  Anyway this is less efficient than being able to allocate registers to parameters and return values.

For varargs from a C compiler, WebAssembly punts already, and fine; varargs aren't common.  But the linear memory solution suggested for varargs is not an option for managed data, and in Lua/Scheme/etc, varargs are common and need GC integration.

I don't know that there is a nice solution here.  I suspect some compilers will emit functions with type:

```
(type $lua1-func (func (param $thr (ref $thread)) (param nargs i32) (param arg0 anyref) (result i32)))
```

i.e. providing a preallocated parameter for the first argument, attempting to pass it in a register for speed.  It's a bit sad though, increasing register and GC pressure across the board.

If there is a nice solution here, it would be good to mention as a possible extension.  If not, perhaps a mention of what these languages need to do is appropriate?  Dunno.

**Comment by lukewagner** [comment]
Setting aside the multi-arity-dispatch use case (which seems harder), the "throw if called with wrong number/types of args" behavior is what we already have when calling an `anyfunc`.  This is currently only possible in the MVP via `call_indirect` on a `Table<anyfunc>`, but if we add a first-class `anyfunc` type (which would follow if we add `get_elem`/`set_elem` on tables), then I would think a dynamically-typed language could use `anyfunc` everywhere.
