### ISSUE TITLE
Agenda for subgroup meeting - March 9

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#196]
The next subgroup meeting is **March 9, 2021 at 9am PST (6pm CET)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

**Comment by rossberg** [comment]
I can give an update on the reference interpreter and show some experimentation I've started with a lab OO compiler to explore different compilation strategies for targeting Wasm GC.

**Comment by tlively** [comment]
Thanks, @rossberg! That sounds great.

**Comment by tlively** [comment]
The notes are in https://github.com/WebAssembly/meetings/pull/731.
