### ISSUE TITLE
Agenda for subgroup meeting - 23rd

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#202]
The next subgroup meeting is **March 23, 2021 at 9am PDT (5pm CET)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

**Comment by tlively** [comment]
Bump! Any agenda items? If nothing comes up by tomorrow morning, we will cancel this meeting.

**Comment by tlively** [comment]
We'll cancel this meeting due to lack of agenda.

**Comment by bashor** [comment]
@tlively you've canceled the meeting on 6th of April instead.

**Comment by tlively** [comment]
@bashor Thanks for catching that! It should be fixed now and my first "fix," which accidentally made the meeting 1 week long, should also be fixed 😅.
