### ISSUE TITLE
Agenda for subgroup meeting - May 4

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#206]
The next subgroup meeting is **May 4, 2021 at 9am PDT (6pm CEST)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please respond to this issue with topics for the agenda.

We have @rossberg tentatively penciled in to present on using isorecursive types rather than equirecursive types.

**Comment by rossberg** [comment]
As a follow-up to last week, I thought I'll first present something about type canonicalisation. Depending on how long that takes, I’ll also talk about iso-recursion, unless somebody else wants to have a slot as well, of course. If not, I’ll do that one next time.

**Comment by tlively** [comment]
Thanks for presenting, @rossberg! The PR for this notes is here: https://github.com/WebAssembly/meetings/pull/770.
