### ISSUE TITLE
Unclear field ordering requirements (prefix subtyping vs. opaque)

### ISSUE THREAD

**Issue by DLehenbauer** [WebAssembly/gc#22]
There is a potentially contradiction between the desire for efficient field access...

> The order of fields is not observable, so implementations are free to optimize types by reordering fields or adding gaps for alignment.

...and below, which suggests ordering fields when subtyping to preserve static offsets:

> A structure type is a supertype of another structure type if its field list is a prefix of the other (width subtyping).

One way to preserve both runtime efficiencies is to have the "prefix rule" takes precedence over the "opaque rule".  (In other words, fields may be reordered/padded/aligned, with the constraint that fields from a supertype must have a binary compatible layout beginning at offset 0.)

Is that a reasonable interpretation?

**Comment by titzer** [comment]
Yes, that interpretation is reasonable, since field reordering is not semantically observable.

E.g. Some JVMs pack or reorder fields for either size or alignment.

**Comment by rossberg-chromium** [comment]
For example, engines are free to reorder fields in whatever way they see fit when they can prove that it won't interfere with any uses of structural subtyping in a given module. Or they use a different (e.g. coercive) implementation of structural subtyping in general. A program can't tell, so it's allowed.

**Comment by rossberg** [comment]
Also did not close this one.

**Comment by tlively** [comment]
Closing this because the original question has been answered.
