### ISSUE TITLE
How can I implements java/lang/Object.clone() ?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#221]
Is there any workaround to implement the feature of java/lang/Object.clone() with one of the beta specs. Can be that I have oversee it?

This feature is a show stopper for the JWebAssembly project.

**Comment by Horcrux7** [comment]
What would occur if I call `Object.assign()` with an Wasm GC object?

**Comment by tlively** [comment]
There is no builtin generic cloning mechanism in the spec proposal, so right now you would have to generate a `clone` implementation for each class

> What would occur if I call `Object.assign({}, obj)` with an Wasm GC object?

The JS API has not been specified, so there's no good answer to this yet. As far as I understand it, the current V8 prototype exposes Wasm GC objects to JS with all of their fields hidden and inaccessible, so my guess is that `Object.assign` would not do anything useful. But this behavior may change in the future.

**Comment by tlively** [comment]
Closing because the question has been answered. If there are further questions, feel free to reopen!
