### ISSUE TITLE
Agenda for subgroup meeting - July 13

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#227]
The next subgroup meeting will be on **July 13, 2021 at 9am PDT (6pm CEST)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda.

So far we have @rossberg scheduled to present on linking issues with nominal types. @rossberg, do you expect that to take the full hour?

**Comment by rossberg** [comment]
I hope it only takes one hour, including discussions. ;)  I'll actually dump most of what I prepared for this week (and perhaps do it another time) -- explaining the compilation schemes can easily fill an hour itself.

**Comment by tlively** [comment]
Sounds good, thanks, @rossberg! It will be good to have plenty of time for discussion.

**Comment by tlively** [comment]
Thanks, everyone! The notes are here: https://github.com/WebAssembly/meetings/pull/827.
