### ISSUE TITLE
Unclear if subtypes are explicit or implicit

### ISSUE THREAD

**Issue by DLehenbauer** [WebAssembly/gc#23]
I was unsure if the proposed type system is explicit about which types are subtypes of which, or if the engine infers subtyping whenever a type definition contains another as a prefix?

The 'extend' expression in examples like the following made me initially think subtyping was explicit...
```
(type $C-vt (struct (ref $f-sig) (ref $gh-sig)))    ;; all immutable
(type $D-vt (struct (extend $C-vt) (ref $g-sig)))   ;; immutable, subtype of $C-vt
```
...but @LeifKo suggested that the above definition for '$D-vt' could simply be shorthand for the following:
```
(type $D-vt (struct (ref $f-sig) (ref $gh-sig) (ref $g-sig)))   ;; Maybe also a subtype of $C-vt?
```
(In other words, 'extend' could just be sugar for duplicating the fields of another type definition.)

For context, this question came up while we were discussing how the engine detects the field ordering constraint for prefix subtyping discussed in #22.

**Comment by rossberg-chromium** [comment]
Yes, the subtyping rules [sketched in the overview](https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md#subtyping) are purely structural. The `extend` syntax isn't explained anywhere, but is supposed to be just a shorthand for an expansion, as @leifko suggests. I will add a note.

FWIW, this is mostly orthogonal to #22. A compiler can still prove that a certain structural subtyping relation is never used in a program, and use that information for reordering.

**Comment by titzer** [comment]
Also, some reordering algorithms (e.g. packing by size) might preserve the structural subtyping property without needing to see the whole program.

**Comment by rossberg-chromium** [comment]
Added note to overview.

**Comment by DLehenbauer** [comment]
(Thanks for the clarification!)
