### ISSUE TITLE
Agenda for subgroup meeting - July 27

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#230]
The next subgroup meeting will be on **July 27, 2021 at 9am PDT (6pm CEST)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda.

Since we didn't get to finish and discuss @rossberg's presentation today, let's plan to continue that next time. Also, since the nominal/structural question is such an important topic, how would folks feel about making this meeting two hours long? My hope is that we will be able to reach agreement on a path forward.

**Comment by RossTate** [comment]
* 👍 this comment if you are okay with a two-hour meeting
* 👎 this comment if you would prefer to not have a two-hour meeting
* 😕 this comment if you are somewhere in the middle

**Comment by igor-laevsky** [comment]
Hi! I send a request through the form several times but didn't receive an invitation. cc @tlively

**Comment by tlively** [comment]
Thanks for that poll, @RossTate! I've updated the calendar and zoom events to make the meeting two hours long.

**Comment by rossberg** [comment]
Thanks everybody for the good discussion. I can present ways to tame type recursion next time (which shouldn't take more than 20 min plus discussion).

**Comment by tlively** [comment]
Thanks for the meeting, everyone! The notes PR is up here: https://github.com/WebAssembly/meetings/pull/839.
