### ISSUE TITLE
Agenda for subgroup meeting - August 10

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#233]
The next subgroup meeting will be on **August 10, 2021 at 9-10am PDT (6-7pm CEST)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Our theme for this meeting will be ways to support structural source types more simply than with separate central linking logic.

Agenda:

  - Taming type recursion [Andreas Rossberg] (20 minutes + 10 minutes discussion)
  - #234 [Ben Titzer] (remaining time)

Also, I will be on vacation, so @ajklein has offered to run the meeting.

**Comment by titzer** [comment]
I think we should also discuss #234 .

**Comment by ajklein** [comment]
@titzer Agreed, I've added this to the agenda and I think that'll easily take up any remaining time after @rossberg's presentation.

**Comment by ajklein** [comment]
Notes PR is up at https://github.com/WebAssembly/meetings/pull/856
