### ISSUE TITLE
Agenda for subgroup meeting - August 24

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#236]
The next subgroup meeting will be on **August 24, 2021 at 9-10am PDT (6-7pm CEST)**. As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda.

**Comment by RossTate** [comment]
The potential discussion items I recall coming up last meeting were:
* @titzer suggested having a poll regarding #234 
* @littledan suggested having a discussion of goals for JS interop (and I started #235 as a warmup)
* @conrad-watt suggested we should at some point have an explicit discussion of encapsulation and privacy

These all seem like good things to make progress on. So maybe we can proceed in that order, moving to the next item when a discussion wraps up, and potentially pushing back any items that we find we don't have time for?

**Comment by tlively** [comment]
Sounds good to me! @titzer, @littledan, and @conrad-watt, would you be prepared to kick off those respective discussions at this meeting?

**Comment by tlively** [comment]
@kripken has also agreed to start us off with an update on recent progress on GC optimizations in Binaryen.

**Comment by titzer** [comment]
Sure, I'll explain and summarize the discussion on the issue so far and carefully-word a poll to get the outcome I want ;)

Ha, but seriously, we should at least get some sense of what people think, so I think a poll is in order.

**Comment by tlively** [comment]
Since we (Google) are already working on nominal typing, we can share our plans for what we're going to look at next as part of that discussion. I agree a poll will be useful to gather general sentiment and align on direction, too.

**Comment by littledan** [comment]
Hey, sorry, I missed this notification until now. @atakikawa and I would be happy to work together on a presentation for the following meeting, but don't really have enough time to prepare something for today.

BTW I'm also going to be giving an overview of this Wasm/JS API design space (in general, spanning the existing API, recent additions, ESM integration, module linking, GC, etc) next week, to hopefully motivate more JavaScript experts to get involved in this area. We will also be discussing a new [fixed-shape object proposal](https://github.com/syg/proposal-structs) in TC39 by @syg , which is intended to be a very rough analogue of Wasm GC within JS. I don't think these efforts introduce any dependencies of one on the other, but I think we'll benefit in design perspective from doing this work in parallel.

**Comment by conrad-watt** [comment]
I'm happy to say a few words to start a discussion on private fields etc, if there's time. Sorry for not responding earlier.

**Comment by titzer** [comment]
Link to my slides: https://docs.google.com/presentation/d/1kq7gPQ_ukj1gcZVliMKZmCiv9f1iV-3q9nJkbPzbYSk/edit?usp=sharing

**Comment by kripken** [comment]
Here are my slides.
[WebAssembly GC Optimization Update (1).pdf](https://github.com/WebAssembly/gc/files/7041133/WebAssembly.GC.Optimization.Update.1.pdf)

**Comment by tlively** [comment]
Thanks everyone! The notes PR is here: https://github.com/WebAssembly/meetings/pull/869. To recap, today we decided:

1. To move ahead with an official (i.e. checked into this repo) prototype spec covering both nominal and structural types.
2. To not consider type or field privacy when determining what the core type system will look like.
