### ISSUE TITLE
Field Accessors

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/gc#238]
This is a suggestion for a different way to design the instructions for getting/setting fields, which for lack of a better term I'll refer to as "field accessors".

## Design

After processing the types section of the module, we'll get *two* lists: the list of types, and the list of field accessors. When processing a (nominal) type in the types section, for every field of the type a corresponding field accessor is automatically added to the field-accessor list. The type of the field accessor depends on the qualities of the field, e.g. what is its value type, and is the field writable? The "receiver" type of the field accessor is whatever (nominal) type it was generated from.

So, if one defines a nominal type, say `$Foo`, with a mutable `i32` field followed by an immutable `i64` field, then there will also be two field accessors, say `$x` and `$y`, where the type of `$x` is "receiver type is `$Foo`, value type is `i32`, and mutability is `mutable`" and the type of `$y` is "receiver type is `$Foo`, value type is `i64`, and mutability is `immutable`". The text format could provider room for declaring the field-accessor names `$x` and `$y`, which get bound to their corresponding indices in the generated field-accessor list.

Then the instructions for getting and setting a field simply include a field-accessor index, rather than both a type and an index. The type of the corresponding field accessor determines the receiver type that must be on the stack and the value type that either is returned (for getting) or must be on the stack (for setting). For setting, the field accessor must also be mutable.

To clarify, this is not the same as the field members described in the Post-MVP. Field members in the Post-MVP are essentially the first-class variant on field accessors.

## Motivation

Short-term reasons to use field accessors:
* **Primary:** Reduces code size without introducing any type-checking complexity: the get/set instructions now have only one index rather than two.
* The names section can give a name to each field accessor, which is helpful for debugging
* I also wouldn't be surprised if it's more straightforward/efficient to compile and interpret.

Longer-term reasons to use field accessors:
* Another way to reduce code size is to simply synthesize the receiver's type rather than explicitly specify its index in the get/set instruction, but that runs into type-checking complexity issues when combined with extensions like multiple upper-bounds (as described in #160), whereas field accessors retain efficient type-checking even in the presence of such extensions.
* Field accessors make it easy for one to import just the fields of another module's types that it actually depends on, and similarly to give other modules access to just the public fields of one's own types without having to also give them access to private fields.

### Accompanying Extension

Field accessors would also facilitate another extension or variation. When one defines a nominal type that extends another nominal type, we could avoid repeating the fields of the other nominal type and simply state the new fields of the new type. In the short term, this would reduce the size of the types section. In the long term, this would facilitate separate compilation of subclasses (particularly in the presence of private fields of the superclass).

Whether we actually want this accompanying extension should be discussed later and somewhere else; I just mention it here as another motivation for field accessors.

## Transfer

Although I came up with this for nominal types, the idea likely transfers to structural types.

**Comment by RossTate** [comment]
I had a chance to consider the hierarchy approach in more depth and was able to make it much simpler than what I described above. That said, I can't figure out how to make the index-only approach to work well with separate compilation. Separate compilation for many object-oriented languages fundamentally relies on being able to build the layout of an object by composing portions of the object that are specified across multiple modules. The "index field from start of object" approach just doesn't accommodate that.

But I think I found a way to synthesize some of the variations above. When you define a new type, you specify just its new fields (relative to the type it extends, if any). To get/set a field, you specify the type and the index of its *new* field. So, if `$C extends $B extends $A`, and `$B` declares three fields "$x: i32, $y: f64, $z: externref", if you want to get the field `$y` of a `$C` reference, you say `get $B $y` (where `$y` is 1). You use 1 for `$y` regardless of how many `$A` fields there are. So it's a slight variation on the current design that works even if `$A` is imported from another module. It's also extensible with more general field accessors. Essentially, when you define a type, its fields are its first field accessors. But you can add more field accessors (though not more fields) later in order to handle nested structures. Similarly, you can import field accessors for an imported type. So the instruction really is `get <type index> <field-accessor index>`, and it happens to be the case that the field-accessor index for newly defined fields of a type is simply their index. So we're essentially building per-type field-accessor tables. I think that would still be interpreter/compiler-friendly, and should compress similarly to (or even better than) the current approach.

Does that make sense?

**Comment by jakobkummerow** [comment]
There is indeed a fundamental incompatibility between fast(est possible) field accesses and separate compilation (or more specifically: unknown supertypes), and we'll have to decide eventually which compromise we want to pick.

The fastest machine code a field load like `struct.get $B $y` can possibly be compiled to (and currently will be compiled to!) is a single instruction:

```
// assume RAX holds the struct
// assume we want the property in RBX
// assume $y's offset from object start is 40
mov RBX, [RAX + 40]
```

When generating this code, the compiler must obviously know the full layout of `$A` and `$B` so that it can compute the final byte offset of field `$y` from the beginning of the object.
If we want to support unknown supertypes, i.e. generate code before the supertype's size is known and not have to recompile it when the supertype changes size, then we have to add an indirection there, which will have a performance cost. We can no longer embed a simple constant like `40`. We may end up with a sequence like:

```
// assume RCX can be used as temp register
mov RCX, [RAX + 0]  // load type info
mov RCX, [RCX + 8]  // load supertype size
// assume $y's offset from $B start is 4
mov RBX, [RAX + RCX + 4]
```

That'd be 3 (chained!) loads instead of 1. I'm not sure this is exactly the code we'd end up with; it's meant to be a representative illustration. I doubt it could be _more_ efficient than this. I also doubt that we'd be happy with a design where _every_ field access has to pay this cost (but that's just my gut feeling).

**Comment by RossTate** [comment]
I agree that we don't want 3 loads for a field access (especially chained ones!). But I don't believe what I'm suggesting here makes that necessary. Let me break it down into cases for `get $B $y`.

First, if you know the full supertype chain for `$B` and all the fields of those supertypes at compile time, you can precompute the offset as you did above. This is the only situation which is currently expressible. That means there is **no performance loss** incurred by this design relative to the current design.

So the real consideration is whether the flexibility granted by this design can be implemented efficiently enough that people would want to use it. Remember that the alternatives are not great. Either you compile the subclass according to a fixed representation of its superclass, or you JIT your own WebAssembly module at load time. And in either case, the module implementing the superclass has to export all the internals of the superclass module just so that you can use its indexing scheme and the linker can check you used it correctly. (Note that both of these are fine for the MVP, as we might not even support separate compilation at all for the MVP, but I'd like an approach that at least is compatible with a good Post-MVP option for separate compilation.) So people might be fine with some pay-as-you-go performance hit for the significant improvement in flexibility&mdash;the key word being *some* (we already have pay-as-you-go per the observation above).

Now let's consider the worst-case scenario. Unfortunately, I'm not sure how you arrived at your first "load type info" instruction, so I can't speak to that. But here's what I would expect. When you import an (extensible/fixed-size) type like `$A`, the module-instance structure would store the size of that type. So first you'd have to load that size from the module instance, then you'd have to add that size, plus the offset of field `$y` within `$B`, to `RAX`, and load from that address. Thus the worst-case scenario seems to be 2 chained loads.

The first thing to consider is that the first load is from the module instance. Presumably this is in the cache (even the L1 cache?). As such, this first load is likely to be (very) fast.

The second thing to consider is that the first load is of immutable data. Thus it can be amortized across loads and writes of various fields of extensions of `$A` in the function. The main cost of this will be register pressure. But, again, since the value is likely in the L1 cache it's not unreasonable to forget it to relieve register pressure and reread it again later. Nonetheless, I suspect that in the common case this value can already be in the register, in which case we implement `get $B $y` with a single load, as before (though with a dynamic offset, which I understand is pretty cheap).

Lastly, I'm still not convinced that WebAssembly can efficiently support even basic ecosystems without some form of instance-specific compilation at the least in the optimizing tier, whether it's inlining, "fusion" (a la Interface Types), or&mdash;in this case&mdash;filling in immediates. But even putting that aside, by the above reasoning I suspect people would find the pay-as-you-go costs to be pretty minor and well worth the flexibility granted, especially with respect to the alternatives. (And, to repeat, it might be that we decide the MVP does not support any separate compilation whatsoever; this design just leaves a path forward for separate compilation in the Post-MVP, with no performance cost to MVP programs, and with other advantages for specifically the MVP discussed above.)

**Comment by jakobkummerow** [comment]
> the module-instance structure would store the size of that type. So first you'd have to load that size from the module instance

I see two implementation options that both lead to three chained loads.
The first is what I described: store all type information on the object (in the RTT/"shape descriptor"). You'd have to get the RTT, then load the offset from it, then do the actual load.
The second is what you've described: keeping a pointer to the instance around, type sizes can be stored on there; realistically that'll be in a separate array though, so the first load would get the "supertypes sizes list" from the instance, the second load would get an entry from that array, and again the third load would do the actual struct field access.

Hardware caching and/or compiler-side de-duping can certainly help; whether it'll help enough to make this viable/desirable will likely have to be determined experimentally at some point.

I didn't mean to imply that the Field Accessors idea in itself requires any of that; I was commenting specifically on separate compilation, with or without Field Accessors.

> I'm still not convinced that WebAssembly can efficiently support even basic ecosystems without some form of instance-specific compilation at the least in the optimizing tier,

Yes, I'm not convinced of that either; giving up on separate/ahead-of-instantiation-time optimized compilation is one of the possible compromises we could choose.

**Comment by RossTate** [comment]
Ah, thanks for the clarifications. But now I have a question about how things are currently implemented. I had thought that WebAssembly modules were designed so that things like globals and imports could be stuck directly in the instance rather than indirectly through arrays (in which case supertype sizes would be in the instance). Is that not the case then? Do gets of globals and calls to imported functions require 2 chained loads in the worst case?

**Comment by jakobkummerow** [comment]
The instance object (like the module object) has a fixed size, so everything whose length is specified by the module is an array: globals, functions, tables, types, you name it. At least we can stick the pointers to those arrays directly into the instance object :-)

Direct-calling an imported function takes 4 loads (two pairs of two chained loads, both best and worst case). Indirect-calling takes 7 (longest chain 3) or 9 (longest chain 4) loads depending on whether the table index is `0` or non-zero, plus two comparisons; whether the callee is imported makes no difference. `call_ref` is currently at 6 loads best case (longest chain 4). (None of this is expected to change in the foreseeable future.)

**Comment by RossTate** [comment]
Oh wow, that's grim. Thanks for the improved understanding (and for clarifying load-count vs. chain-count).

**Comment by titzer** [comment]
Keep in mind that globals can be imported/exported, so their storage needs to be indirected from instances.

I don't understand why `call_ref` is 6 loads, can you explain?

**Comment by aardappel** [comment]
9 loads worst case, wow! The cost of just even a small bit of abstraction/indirection is intense!

I presume part of this is because we must accommodate an imported function to be changed at any moment? What if we had a way to "seal" a Wasm module after instantiation?

**Comment by jakobkummerow** [comment]
@titzer Pseudo-code for `call_ref` is:
```
// Given (dynamic): func_ref, current_instance
if (func_ref == null) { Trap() }  // optimized away if statically provable
shared_info = Load(func_ref, kSharedFunctionInfoOffset)
func_data = Load(shared_info, kFunctionDataOffset)
instance = Load(func_data, kRefOffset)
instance_map = Load(instance, kMapOffset)
instance_type = Load(instance_map, kTypeOffset)
if (instance_type == Pair) {
  Store(instance, kValue1Offset, current_instance)
}
target = Load(func_data, kTargetOffset)
if (target == kNull) {
  target = Load(func_data, kWrapperOffset) + kInstructionStart
}
Call(target, instance)
```
The conditional `Store` (which is needed for calling funcrefs referring to JS functions) is particularly ugly; but it's much better than the allocation that was there before I optimized it to its current state.

A lot of this complexity is due to the fact that V8 is both a Wasm and a JS engine (and a funcref can come from either world); in a pure-Wasm engine this could be a lot simpler.

**Comment by titzer** [comment]
Imported functions can't be changed, but tables can. `call-indirect` is complex because of signature checking and the possibility of a cross-module call. TurboFan generates all of that inline, but most of it could be moved out-of-line into a per-signature stub.

**Comment by titzer** [comment]
@jakobkummerow Ah, yes, I hadn't considered JS functions flowing into a wasm call ref and then presumably escaping again via `anyref`. There are several ways of increasing intrusiveness that can make that sequence better:

1. Add a field to JSFunction objects that is essentially a pointer to an entrypoint specifically for wasm `call-ref`.
2. At the boundary between JS and Wasm, i.e. all wrappers, coerce `JSFunction`s into a different representation (e.g. by having an additional field that points to a wasm closure, which also points back, for identity).

The second one implies doing work for every reference (not statically known not to be potentially a JSFunction) that crosses between JS and Wasm, either at a function call, or being written or read from a table.

Thanks for the info, though I did drag this a bit off topic.

**Comment by jakobkummerow** [comment]
re 1: Yes, putting another pointer (or two) into JSFunction could save a load (or maybe two?), but given all the efforts we've put into making JSFunctions as small as possible (because there are typically many of them), I'm hesitant to make them bigger.
re 2: Interesting idea, I'll have to think through that (including whether that can be pulled off without making JSFunctions bigger).

**Comment by rossberg** [comment]
My assumption for function references always was approach (2), i.e., coerce at the boundary, like you do for imports. With that, `call_ref` should be no slower than a regular `call` to an imported function. In fact, shouldn't it be faster, because it saves the load from the import/func array?

**Comment by tlively** [comment]
Is anyone interested in investigating this option further? If not, we can close this issue.

**Comment by titzer** [comment]
I don't think object models will work exactly along the lines in this thread, but I can see a use case for importing field accesses. That said, there are several issues in this thread and I think the `call.ref` overhead has been addressed elsewhere. I'd be OK closing this issue.

**Comment by tlively** [comment]
Now that we're in phase 3, the design is largely stable, so we won't be adding field accessors to the MVP. If it would make sense as a post-MVP feature, PRs it to the [post-MVP doc](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Post-MVP.md) would be very welcome.
