### ISSUE TITLE
Agenda for subgroup meeting - September 21

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#240]
The next subgroup meeting will be on **September 21, 2021 at 9-10am PDT (6-7pm CEST)**.  As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda.

So far we have one carry-over item which is a discussion of separate compilation capabilities led by @RossTate.

**Comment by takikawa** [comment]
I was wondering if I could book a very small slot (~5 minutes or even less) at the beginning or end to advertise a relevant event. There is a TC39 incubator call [next week](https://calendar.google.com/calendar/event?eid=MmNkNWwybTNrdXRxYzN2M205c2YwM3FoZTcgbW96aWxsYS5jb21fbDdiNTBpdHBhYTlibnJ2cjYxbmVicXJuZThAZw&ctz=America/Los_Angeles) on the 23rd to discuss WebAssembly and JavaScript interoperation in general and I thought it might be of interest to GC subgroup attendees.

**Comment by tlively** [comment]
Sounds good to me, @takikawa! In case something else comes up, @RossTate, how much time would you like at minimum for the discussion you are leading?

**Comment by RossTate** [comment]
It'd be nice to have enough time for the group to discuss and come to a consensus, so say 30 minutes (including presentation?

**Comment by tlively** [comment]
Sounds good. It looks like nothing else has come up, so we'll have as much time as we need.

**Comment by RossTate** [comment]
Turns out we've *just* finally finalized some experiments we've been doing on ahead-of-time compilation that would be useful to present. Shouldn't take long: 15 minutes.

**Comment by tlively** [comment]
Thanks everyone! The notes are here: https://github.com/WebAssembly/meetings/pull/879.
