### ISSUE TITLE
Agenda for subgroup meeting - October 5

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#244]
The next subgroup meeting will be on **October 5, 2021 at 9-10am PDT (6-7pm CEST)**.  As with other Wasm meetings, we'll host this on Zoom.

No registration required if you attended a previous meeting. Fill out the form here if it's your first time: https://forms.gle/JehrAB4gWbtHjybt9.

Please reply with topics for the agenda and the amount of time you'd like to spend on them.

**Comment by askeksa-google** [comment]
If there is interest, I can talk about `dart2wasm`, highlighting some of the relevant challenges and design decisions of the project. 20-30 minutes would be appropriate, I think.

**Comment by conrad-watt** [comment]
Given the current conversation in https://github.com/WebAssembly/gc/pull/243, it may be useful to have a brief discussion/vote to clarify the intentions of the 08/24 resolution to prototype a nominal proposal. I think it's clear from the [meeting notes](https://github.com/WebAssembly/meetings/blob/main/gc/2021/GC-08-24.md#discussion-evaluating-nominal-types-ben-titzer-20-minutes) that we were also expecting to prototype Andreas' revised structural proposal (or at least, something better than the current equi-recursive proposal), but the text of the previously agreed resolution may not reflect this.

**Comment by tlively** [comment]
Sure, let's plan to spend 10-15 minutes discussing concrete implementation and investigation plans.

**Comment by tlively** [comment]
Not an agenda item, but a related announcement: I plan to provide an overview of our progress on the proposal to the wider CG at the October 12 meeting (https://github.com/WebAssembly/meetings/pull/889). @kripken and @jakobkummerow will be joining me to talk about the Binaryen optimizations and V8 side of things as well. Please let me know if you'd like to present progress on your own related GC work and I can add you to the presentation.

**Comment by tlively** [comment]
Thanks for the presentation, @askeksa-google! The notes PR is here: https://github.com/WebAssembly/meetings/pull/893.

We didn't get to discuss our concrete prototyping or investigation plans in this meeting, but I've [written](https://github.com/WebAssembly/gc/pull/243#issuecomment-934707073) my current thoughts on #243, so I hope we can continue the discussion there.
