### ISSUE TITLE
Immutable arrays?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#250]
The spec does not allow immutable arrays atm. When optimizing things for j2wasm we noticed that it seems like we could support them, if we have `array.init` which takes the values to initialize with, which is also being experimented with.

It seems like the rules for an immutable array could be like those of a struct, that is, subtypes would need to match it precisely on everything? Structs can at least add more fields, but not arrays, so this makes subtyping less useful in the array case, of course. Still, immutable arrays can be useful because of things like itables: An itable call does a read from an array that is in practice immutable, so if the toolchain and VM know it is immutable that can help.

Opening this issue for thoughts as we look into experimenting with it.

**Comment by jakobkummerow** [comment]
I support this.

I think you have a mixup in the subtyping description: for _mutable_ arrays, subtypes have to match the field type exactly. For _immutable_ arrays, subtypes of the array can specify a non-trivial (non-identical) subtype for the field type. The mutability attribute itself must be identical in a subtype and its supertype. The summary is what you said: arrays would then behave for subtyping like structs with a single field.

**Comment by manoskouk** [comment]
The instruction you are describing is pretty much the same as `array.init` that we are experimenting with in V8. The only difference is that we do not allow an additional length argument. I think its use is not that niche, as you can define constants for types which are generally represented as arrays of arbitrary length, e.g. strings.
We have set the limit of N to 999, which, as you suggested, is arbitrary. To circumvent this limitation for string constants, we are discussing loading elements directly from raw bytes as opposed to a series of `i32.const`, through some sort of data segment, or maybe immediate arguments.

**Comment by tlively** [comment]
> > > Note: in the MVP, all arrays must be defined as mutable
> 
> ... I believe it was meant to talk about arrays, not array types per se, otherwise there would have been an explicit condition about `<fieldtype>`. But then it should better say "created" not "defined". That said, I'd be fine to resolve it either way.

@rossberg, I still don't understand what this note would mean if it read "all arrays must be created as mutable." It would be great to clarify this language in the doc; I think that's the only thing preventing us from closing this issue.

**Comment by jakobkummerow** [comment]
Now that we have `array.new_fixed` and `array.new_data`, we should allow immutable arrays. We all agreed that the only reason not to have them was that there was no way to create them (with non-default values), but that's no longer the case. 

IIRC they are useful in particular for `itable` implementations, where the immutability helps toolchains/engines apply optimizations/inferences.

**Comment by rossberg** [comment]
What @jakobkummerow said. The note was obsolete and I just forgot to remove it. Done now.

**Comment by tlively** [comment]
Great, I'll close this issue, then.
