### ISSUE TITLE
Unable to create a file in physical hard disk

### ISSUE THREAD

**Issue by prestigecodehub** [WebAssembly/gc#255]
Requirement: Requirement is to create a file on physical hard disk using C/C++ API's(fopen(), fread(), fwrite() etc) and dump the data in to that for our reference.
Issue: Unable to create text file using C/C++ API's using in webassembly.
Below are the few references used and followed the same steps but couldn't succeed.
1. https://emscripten.org/docs/api_reference/Filesystem-API.html
2. https://github.com/emscripten-core/emscripten/blob/main/tests/fs/test_append.c
3. https://github.com/emscripten-core/emscripten/blob/main/tests/fs/test_write.cpp
4. https://emscripten.org/docs/getting_started/Tutorial.html#tutorial-files
and other related article, but finally understood that as part of complication emscripten  tool is creating virtual memory and data is read during subsequent operations.
I really appreciate any suggestion/support on my requirement.
Code snippet for your ref:
Test -1:
    EM_ASM(
        var stream = FS.open('testfile', 'w+');

        var data = new Uint8Array(128);
        var str = "Hello! ";
        stringToUTF8Array(str, data, 0, lengthBytesUTF8(str)+1);
        data = data.subarray(0, lengthBytesUTF8(str));
        FS.write(stream, data, 0, lengthBytesUTF8(str), 0, /*canOwn=*/true);
        var pos = lengthBytesUTF8(str);

        str = '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890';
        data = new Uint8Array(100);
        stringToUTF8Array(str, data, 0, lengthBytesUTF8(str)+1);
        FS.write(stream, data, 0, lengthBytesUTF8(str)+1, pos, /*canOwn=*/false);

        FS.close(stream);
    );

    std::ifstream file("testfile");
    std::string line;
    getline(file, line);
    std::cout << "read " << line << std::endl;

Test-2:
      FILE *fPtr;
      fPtr = fopen("tests/sample.txt", "a+");
      /* fopen() return NULL if unable to open file in given mode. */
      if (fPtr == NULL)
      {
         /* Unable to open file hence exit */
         printf("\nUnable to open '%s' file.\n", "tests/sample.txt");
         printf("Please check whether file exists and you have write privilege.\n");
         exit(EXIT_FAILURE);
      }
      /* Append data to file */
      fputs(dataToAppend, fPtr);
      /* Done with file, hence close file. */
      fclose(fPtr);

**Comment by rossberg** [comment]
Closing this as off-topic.

**Comment by prestigecodehub** [comment]
> Closing this as off-topic.

Hi Andreas Rossberg,

Sorry for creating off topic issue. I would be happy if you could provide any suggestion on above queries.

**Comment by kripken** [comment]
@prestigecodehub This looks off-topic because your question is not about wasm GC (this repo), but even the main wasm repo would not be right since all your links go to emscripten docs. That is, this looks like an emscripten question, which should have been opened there.

But if you want to create a file in the outside filesystem, the relevant options in emscripten are NODEFS and NODERAWFS, which use node APIs to access the system's files, https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api-nodefs
