### ISSUE TITLE
Type code clash for `array` and function type constructors

### ISSUE THREAD

**Issue by rossberg** [WebAssembly/gc#269]
#264 added the arrayref type, following the V8 implementation. However, this reuses the type code -0x20 (0x66) for the array heap type, which is already used for function types. In the presence of type exports, we will likely need to allow abstract heap types like `array` in type definitions, so this clash is a problem.

I suggest changing to -0x1a instead, which was skipped anyway.

**Comment by jakobkummerow** [comment]
Looks like that's a typo in our document: 0x66 (which is how V8 implements it) is indeed -0x1a, not -0x20. (I've just fixed the typo in the doc.)

**Comment by rossberg** [comment]
Okay, cool, thanks for the quick reply!
