### ISSUE TITLE
Java Reflection

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#289]
I am trying to implement Java Reflection field access.

Is there any solution for `struct.set/get` with a dynamic field index and dynamic type id from stack to access the fields of a struct? The instruction `struct.set/get` work with fix values.

Also the POST-MVP field access https://github.com/WebAssembly/gc/blob/main/proposals/gc/Post-MVP.md#field-references required that the values are hard coded in the `ref.field`

The only workaround I see at the moment is two additional functions for each field in the theoretical event that someone accesses it at runtime via reflection.

**Comment by tlively** [comment]
Yep, adding those additional synthetic functions is going to be your best bet. We don't have any plans for "native" reflection because that would make engines much more complicated and inhibit a bunch of optimizations.

**Comment by Horcrux7** [comment]
This is a large overhead. This will fill the wasm file with many code that will never use.

**Comment by tlively** [comment]
If you optimize the module with Binaryen, it should be able to prove that most of the synthetic functions are unused and remove them. Where reflection _is_ used there will still be overhead, but it's better that the overhead be explicit and opt-in on the toolchain level rather than built into the spec where it will affect all toolchains.

**Comment by titzer** [comment]
The problem with Java reflection is that you cannot guarantee ahead-of-time that program elements will be reflected on. JVMs typically dynamically generate bytecode for this. In Wasm, this would entail dynamically generating a new module that repeats the struct definition and exports a function that accesses a given struct index. If we had type imports and field imports, then you could have this module just once and instantiate it multiple times.

**Comment by Horcrux7** [comment]
@tlively Reflection can't optimize at compile time. That a tool like Binaryen can't optimize any in such case. My compile make already a flow analyze and compile only the needed functions.

@titzer You suggest to create a webassembly module to access dynamically fields? Wau! If this is possible then reflection already exists. And this can better optimized?

**Comment by titzer** [comment]
@Horcrux7 In order to do this, you must call out to the host environment, e.g. in JavaScript, which has the `WebAssembly.Module` constructor (and `compile()`). You wouldn't be able to do this yet, e.g. in WASI.

**Comment by tlively** [comment]
Closing this since the question has been answered, but feel free to reopen if you have any follow-up questions, @Horcrux7!
