### ISSUE TITLE
array.new_fixed has length as u32, not ULEB32

### ISSUE THREAD

**Issue by titzer** [WebAssembly/gc#305]
The binary encoding for `array.new_fixed` length seems to be a `u32` (i.e. 4-byte integer), rather than an LEB. I think this should be an LEB.

**Comment by rossberg** [comment]
You mean in the Overview? The spec defines `uN` (and `sN`) to encode as an LEB (since no other encoding occurs in Wasm).

But indeed, there was a bug in the interpreter. Now fixed.

**Comment by titzer** [comment]
Thanks!
