### ISSUE TITLE
[interpreter]: Crash on access of null i31ref

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/gc#308]
The following example interpreter interaction crashes with an internal error (I had expected a trap):

```
wasm 2.0 reference interpreter
> (module (func (export "f") (result i32) (i31.get_s (ref.null i31))))
module :
  type 0 = func [] -> [i32]
  export "f" : func 0
> (invoke "f")
stdin:1.41-1.67: runtime crash: missing or ill-typed operand on stack (null : [(ref null i31)])
```

It looks like the behavior of `i31.get_<sx>` is currently underspecified for the null case in the explainer:

> * `i31.get_<sx>` extracts the value, zero- or sign-extending
>   - `i31.get_<sx> : [i31ref] -> [i32]`

Would it make sense to specify this case as trapping?

**Comment by rossberg** [comment]
Yes, definitely makes sense. This was an oversight in #277, when I changed i31ref from meaning `(ref i31)` to `(ref null i31)`. Fixed by #309.
