### ISSUE TITLE
Weak references

### ISSUE THREAD

**Issue by serprex** [WebAssembly/gc#31]
I'm not seeing any mention of weak references

From the perspective of Lua there'd be a desire to be able to essentially toggle the weakness of a table's keys or values when updating the metatable. But that's pretty specific flexibility. I'd expect at least a weakref type for structs which the runtime can null out when the target becomes otherwise unreachable

Also destructors

**Comment by rossberg** [comment]
Good point. I added a section on weak refs and finalisers to the overview, pointing out that it is quite difficult to come up with a good design that covers sufficient ground to be generally useful. Thus, while definitely desirable, I'm not sure whether weak refs will be in the first iteration of a GC proposal.
