### ISSUE TITLE
Does i31.get_{s,u} take (ref i31) or (ref null i31)?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#312]
It's documented as taking `i31ref`, but the meaning of that has changed. V8 seems to currently expect a (ref i31), but I suspect it should be updated to take (ref null i31).

**Comment by rossberg** [comment]
That's correct. It's now consistent with the typing of similar instructions for structs and arrays.

**Comment by rossberg** [comment]
I just tweaked the MVP doc to expand out the uses of i31ref for more clarity, also fixing the return type of `i31.new`, which is meant to produce a non-null i31.

FWIW, there also have been tests for all this, see gc/i31.wast.

**Comment by tlively** [comment]
Thanks!
