### ISSUE TITLE
Text format: function types implicitly defined by type uses

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#344]
For type uses without an explicit type name, Binaryen's current implementation only uses an existing matching function type if it is in a recursion group of size one, i.e. if it is the same type that would have been implicitly defined had there been no previous definitions. However, it's reported in https://github.com/WebAssembly/binaryen/issues/5355 that the reference interpreter uses existing function types with the same signature, even if they are not in a singleton rec group.

This seems like a bug in the reference interpreter, but perhaps it's intentional?

**Comment by rossberg** [comment]
Not intentional, it's a bug in the parser's processing of recursion groups, whose elements end up all being recorded as singletons in the environment. Will fix.

**Comment by rossberg** [comment]
Couldn't let the rest, so here goes a fix: #345
