### ISSUE TITLE
Question: is there Wabt-Tooling available for the GC proposal?

### ISSUE THREAD

**Issue by mirkosertic** [WebAssembly/gc#349]
Hi@all,

I'd like to test the GC MVC implementation. Is the Wabbit tooling already ready to support the MVP textual representation? The latest release of Wabbit GC support seems to be very outdated. Could someone give be a hint about where to start? I need a wat2wasm compiler, or at least some working example in binary and textual representation, as a starting point.

Thanks in advance,
Mirko

**Comment by jakobkummerow** [comment]
You can use Binaryen to convert .wat to .wasm for GC-using modules: either the `wasm-as` or `wasm-opt` binary, with `--enable-gc` or `-all` flag, I'm not sure whether `--hybrid` is also still required.

**Comment by mirkosertic** [comment]
Thank you for the hint. I had to use `--enable-gc --enable-reference-types` with `wasm-as` to make it working!
