### ISSUE TITLE
Clarification on array element operations 

### ISSUE THREAD

**Issue by manoskouk** [WebAssembly/gc#350]
Say we call `array.new_elem` twice on the same elements of the same segment. Should the resulting respective array elements be pointer-identical?

**Comment by jakobkummerow** [comment]
To clarify: the interesting case is when an element definition contains an allocation instruction like `struct.new` or `array.new`. Should that allocate a single object (as if it was a global initializer), or should that allocate a fresh object every time something is initialized from this element segment?
If the former, are we concerned that some users of this shared object might modify it (i.e. its struct fields or array elements), which other users might not expect?

**Comment by rossberg** [comment]
A segment is an immutable list of references that is evaluated and initialised only once, when the module is instantiated, see Step 9 of [module instantiation](https://webassembly.github.io/spec/core/exec/modules.html#instantiation) in the spec. That's not changing. If a module has segments referencing mutable heap objects and does not want those to be shared, then it shouldn't share them. If it needs fresh references, segments are the wrong tool.

**Comment by manoskouk** [comment]
Thanks for clarifying!
