### ISSUE TITLE
array.new ordering in the docs

### ISSUE THREAD

**Issue by kripken** [WebAssembly/gc#351]
The [MVP doc](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md) says
```
array.new_canon $t : [t' i32] -> [(ref $t)]
```
But the [Overview doc](https://github.com/WebAssembly/gc/blob/main/proposals/gc/Overview.md) says
```
Arrays are allocated with the array.new instruction that takes a length and an initialization value as operands, yielding a reference:

(func $g
  (call $f (array.new $vector (i32.const 1) (f64.const 3.14)))
)
```

**Comment by tlively** [comment]
We should consider deleting replacing the overview doc with the mvp doc. @rossberg, is there any reason not to do that?

**Comment by rossberg** [comment]
Yeah, the overview isn't entirely up to date. But the MVP doc is not a real replacement, since the overviews contains all the rationale, explanation, and examples, whereas the MVP doc is mostly limited to draft spec text.

**Comment by rossberg** [comment]
This should be fixed in the Overview now.
