### ISSUE TITLE
Should we allow `global.get` of mutable globals to be constant?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#357]
The GC proposal already extends constant expressions to allow `global.get` to access non-imported, immutable globals, but we could take that further and allow access to imported and non-imported mutable globals as well. I don't have a particular production use case in mind, but I would appreciate this extra flexibility in writing the bulk-array spec tests, for example.

**Comment by rossberg** [comment]
Reading mutable state is an effect, so it doesn't truly qualify as a const expression. It needs to be ordered wrt write accesses to the global. For example, making that order observable would affect possible lazy evaluation strategies for complex initialisers. It's probably better not to cross that bridge if there isn't a pressing need.

**Comment by tlively** [comment]
Ah, I hadn't considered lazy evaluation. Are there any engines that do that?

I'll close this issue, though, since I agree the benefit doesn't outweigh that cost, even if no engine were doing lazy evaluation at the moment.
