### ISSUE TITLE
Structs/arrays proposal

### ISSUE THREAD

**Issue by dy** [WebAssembly/gc#366]
(Sorry for possibly naive opinion and question)

The GC proposal even in MVP form looks massive - complex for users, big work for implementors, somewhat undermines the "static" spirit of WASM.
I'm curious wouldn't that be smoother transition to have simple structs proposal first that could be implemented in similar to multiple return values way? Just _struct_ and _array_ types. It would make a big deal from user-facing API point.
Was that idea considered / what were the objections?

**Comment by rossberg** [comment]
That's pretty much what it is. The rest of what you see are just type system features needed to support structs/arrays without imposing runtime type checks on every access.

**Comment by dy** [comment]
Got it. I imagined something trivial, like linear memory layouts, not closures, methods, generics/polymorphism, recursion, i31 etc.

**Comment by rossberg** [comment]
Other than i31, which is utterly simple, none of things you list are part of the current proposal.
