### ISSUE TITLE
Subgroup meeting on Tuesday, April 18

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#368]
Just wanted to broadcast the agenda for Tuesday's [subgroup meeting](https://github.com/WebAssembly/meetings/blob/main/gc/2023/GC-04-18.md).

So far we have:

 1. @wingo presenting on compiling Scheme to WasmGC
 2. A discussion to finalize the branching cast instructions

Hope to see everyone there!

**Comment by rossberg** [comment]
Just a heads-up that, unfortunately, it's most likely that I will not be able to attend next Tuesday (I'm at an in-person event). So it might be worth considering to move the cast discussion.

**Comment by tlively** [comment]
Thanks for the heads up, @rossberg. I'll move the discussion of the branching cast instructions to the next meeting.
