### ISSUE TITLE
`extern.internalize` differences a compat hazard?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#369]
In the JS embedding, `extern.internalize` returns values dynamically typed as `anyref` or `i31ref`. This suggests that other embedders would be free to return values with any other subtype of `anyref` as well. For example, an embedder might choose to internalize values into concrete struct or array types rather than opaque values. Portable modules must not assume internalized references are anything more specific than `anyref`, although it would be possible to write non-portable modules that do make assumptions, for example by always casting the result of `extern.internalize` to `i31ref` or some other type.

Are we concerned about different embeddings having different `extern.internalize` behavior being a compatibility hazard?

**Comment by titzer** [comment]
I agree that internalizing host values is inherently going to be host-dependent behavior. What matters is the internalization of externalized Wasm values. Perhaps we should specify that `internalize(externalize(val)) == val`?

**Comment by titzer** [comment]
Hmm, I don't quite see how the Wasm specification will achieve that it if it specifies neither the representation of host values nor the mapping of Wasm values to host values. Probably splitting hairs here, but I don't see how the specification can say anything more precise than the internalize ∘ externalize is identity, since it seems host value equivalence can't be specified by Wasm either.

**Comment by tlively** [comment]
Good point that we already get this situation from internalizing externalized values. It still seems possible for there to exist a compatibility hazard, but the solution would be to standardize the internalized types of values above the layer of the Wasm core spec, just like the JS embedding spec does. For example, if a WASI API returns an `externref`, it should probably also specify the precise internalized type of that externref as well. That doesn't play well with virtualization, though, so it would actually have to specify only an upper bound on the internalized type, and then the compat hazard becomes possible again.

**Comment by tlively** [comment]
Is there any more to say about the potential compat hazard here, or can this be closed?

**Comment by tlively** [comment]
Closing, feel free to reopen for further discussion.
