### ISSUE TITLE
Issues with JavaScript spec tests

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/gc#396]
I've run the current version of the JavaScript tests in this repo in V8, and encountered a couple of issues.

(1) (Inherited from the "function-references" proposal repository?) The (generated?) function `assert_return()` has a bug in the `"ref.null"` case, where it treats `actual` as a scalar value, but it's actually an array (see other `case`s in the same `switch` for comparison). In other words, in the snippet:
```
case "ref.null":
        if (actual !== null) {
          throw new Error("Wasm null return value expected, got " + actual);
        };
```
both occurrences of `actual` should be `actual[i]`. This makes the following tests fail:
- ref_null
- table

(2) The function `assert_return()` is also called a couple of times to handle cases `"ref.i31"`, `"ref.struct"`, `"ref.array"`, `"ref.eq"`, which aren't implemented at all. Presumably it's meant to perform type checks; these type checks cannot be expressed in JS, so appropriate exported Wasm functions would have to be defined in some helper module. This affects the following tests:
- array
- i31
- struct

(3) A number of test cases are trying to call a JS function named `hostref()`, which doesn't exist. This affects:
- br_on_cast
- br_on_cast_fail
- br_table
- elem
- extern
- global
- local_init
- ref_cast
- ref_is_null
- ref_test
- select

(4) The test `linking`, as far as I can tell, generates a broken module that tries to read type definition $3 from a type section that only has entries $0, $1, and $2. The invalid module very much doesn't match the module defined in the `.wast` source of the test, and I don't know where it's coming from, and I may well be missing something, but at any rate the test doesn't pass.

Note: if you want to repro, you'll have to hack around the fact that V8 uses the binary encoding defined in https://bit.ly/3cWcm6Q, which doesn't entirely match the encoding defined in MVP.md and used by the tests. This affects a handful of struct/array operations, and the `nofunc`/`noextern` types. This discrepancy will of course be ironed out in the upcoming big reshuffling.

**Comment by rossberg** [comment]
Thanks. Yes, this is expected to be buggy, since there was no way to properly test it so far. Thanks for the detailed report, I'll look into it.

**Comment by rossberg** [comment]
@jakobkummerow, (1)-(3) are easy to fix, but can you provide a bit more information regarding (4)? Which test specifically in linking.wast are you referring to?

**Comment by rossberg** [comment]
Ah, I think I found the cause for (4). All issues should be fixed by #398.

**Comment by rossberg** [comment]
I merged #398, please let me know if there are still issues.

**Comment by tlively** [comment]
@jakobkummerow, could you try this again and see if there are any more issues?

**Comment by tlively** [comment]
friendly ping @jakobkummerow

**Comment by jakobkummerow** [comment]
Looks like #372 forgot to update the non-prefixed opcodes in the interpreter: both `encode.ml` and `decode.ml` still think that `0xd3` is `ref.as_non_null`, whereas it should mean `ref.eq` now (per MVP.md). Accordingly, `0xd4` and `0xd5` also need updating.

The "packed types" `i8` and `i16` are also not updated to their final encoding (e.g. [Pack8](https://github.com/WebAssembly/gc/blob/main/interpreter/binary/encode.ml#L156) still says `-0x06` when it should say `-0x08`; and once again `decode.ml` has the same issue).

FWIW, the current set of failing tests is:
- array
- array_copy
- array_fill
- array_init_data
- br_on_null
- br_on_cast
- br_on_cast_fail
- extern
- ref_as_non_null
- ref_cast
- ref_eq
- ref_test
- struct
- unreached-valid

To run tests yourself, you can take a V8 checkout and patch in https://chromium-review.googlesource.com/c/v8/v8/+/4756846 (e.g. using `git cl patch -f 4756846`, or by manually downloading the patch from Gerrit if you prefer).

**Comment by tlively** [comment]
@jakobkummerow, those encoding problems should be solved by https://github.com/WebAssembly/gc/pull/414, which I've just landed TBR to unblock further work here.

**Comment by jakobkummerow** [comment]
The spec tests are passing in V8 now (with crrev.com/c/4756846 applied to get the final binary encoding). Thanks!
