### ISSUE TITLE
Clarification on ToWasmValue for i31ref

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/gc#399]
[Source](https://webassembly.github.io/gc/js-api/index.html#towebassemblyvalue).

```
Else if v [is a Number](https://tc39.github.io/ecma262/#sec-ecmascript-language-types-number-type) and v is equal to ? [ToInt32](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-toint32)(v) and [ℝ](https://tc39.github.io/ecma262/#%E2%84%9D)(v) < 230 and [ℝ](https://tc39.github.io/ecma262/#%E2%84%9D)(v) ⩾ -230,

    Let r be [ref.i31](https://webassembly.github.io/spec/core/exec/runtime.html#values) v.
```

For the final step, we construct a `ref.i31`, which takes a `u31` parameter, with `v` which is a JS number. From the pre-conditions, `v` is an integer within the range [-2^30, 2^30), so it may be negative. What happens to negative Numbers when they're converted to u31? It feels like an explicit conversion is missing here from JS number to u31.

**Comment by rossberg** [comment]
Hm, I don't disagree, but the same question already seems to apply for conversions to MVP types i32 and i64. I believe all three of them need to perform a 2's complement for negative numbers (i.e., apply the inverse of the Wasm `signed` meta-function).

**Comment by tlively** [comment]
What is the next step to resolve this? An initial PR fixing it in the upstream spec followed by a fix here? Who would like to own this?

**Comment by rossberg** [comment]
I created #411 to fix everything here. Somebody may want to upstream the non-i31 pieces of that fix to the main repo, or we just wait until GC is merged. :)

**Comment by eqrion** [comment]
@rossberg Yeah, that was the interpretation we settled on as well. Thanks for fixing this.
