### ISSUE TITLE
Run-Time Types: Separating Requirements from Guarantees

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/gc#41]
The current proposal (meaning with PR #38) seems to conflate two important aspects of run-time types. Or at least, its run-time types seem like they're supposed to be analogous to gc headers, and the proposal doesn't recognize two aspects of gc headers.

In a garbage-collected language with dynamic casting, the gc header does (at least) two things: informs the gc how to manage the memory, and provides a way to dynamically check whether the memory has some additional previously-agreed-upon structure. The latter provides dynamic guarantees, whereas the former requires static structure, so I'll call the latter guarantees and the former requirements.

My understanding as that `struct.new_rtt $t t' : [(rtt t') t*] -> [(ref $t)]` is supposed to allocate some memory with the `rtt` value on the stack as its gc header. (At least that's conceptually what's going on, but there's likely going to be some more behind-the-scenes machinery happening here that I'll ignore to simplify the discussion.) However, that can't be done because the required relationship between `t'` and `$t` is too weak to ensure that the `rtt` value can inform the gc how to manage the new struct. For example, the new struct can have fields that `$t` doesn't say anything about.

So this means that every structure will need to have at least two fields of meta-information: one for dynamic casting and another for garbage collection. Note that, for OO languages, since the proposal doesn't provide a way to bundle the vtable pointer into either of these fields of meta-information, every object will effectively need to have three fields of meta-information. But this is fixable. Here I'm going to just focus one collapsing the casting and gc meta-information; I'll leave the vtable fix for another issue.

The fix is pretty simple. The `rtt` type constructor should have two arguments: its required type and its guaranteed type. `rtt` is conceptually invariant with respect to its required type and covariant with respect to its guaranteed type. The required type should be a subtype of the guaranteed type. `struct.new_rtt` should then ensure that the stack matches up exactly with the required type. On the other hand, `cast` only dynamically ensures the guaranteed type, not the required type. `rtt.new` similarly should only require that the guaranteed types are subtypes.

Note that it's now unclear what the role of `rtt.anyref` and such are. I suspect that either they are captured by some extensions to what I've proposed here or their role has something to do with the uncastable references I talk about in #39.

**Comment by RossTate** [comment]
Okay, my fix makes what you describe possible: the browser can implement mine with descriptors and rtts as separate things or as unified things. The current MVP, however, forces them to be separate things for the reasons I pointed out above. So my fix gives more freedom to the browser.

**Comment by rossberg** [comment]
RTTs are not only stored in objects, they occur in other roles, too. What would the extra parameter to the rtt type mean in the role as a target type for a cast, for example? It seems to me that your proposal couples the two separate concerns I mentioned. Does it have a useful semantics outside this specific use as object tags?

**Comment by RossTate** [comment]
So what I proposed was the smallest thing that would enable the necessary components. More generally speaking, there are three attributes that the tag on the memory does: gc info, casting, and application-specific metadata. Not all tags need to do all three things, but for space-efficiency purposes it's important to be able to have tags that can do all three things. Of course, the browser could always choose to implement it a unified tag as three separate tags, but that's its choice. However, a browser can't take three separate tags each developed for a different purpose and efficiently combine them into a unified tag.

Of course, recognizing that a tag can have these three separate purposes suggests an obvious subtyping lattice. So the obvious extension to my proposal is to fill in the various combinations. That way languages that need only some of these components can specify just those aspects that they care about, giving even more flexibility to the browser.

Another way to think about it is that I'm requiring wasm programs to specify more *intent* (as opposed to more implementation), which makes it easier for the browser to implement that intent more efficiently (and in more ways).

**Comment by lukewagner** [comment]
Actually, I also see an implementation hazard (which no doubt we'd have hit immediately when we got to actually prototyping this part of the proposal), although it's not quite the one Ross describes:

The idea behind `rtt` values is that they are just pointers to already-constructed Shapes (aka Maps or Hidden Classes).  So ideally, when you execute `struct.new_rtt`, the VM just GC-allocates the header and assigns the `rtt` Shape pointer to the new object's header field&mdash;no branching (other than GC alloc).  But if the complete object type is a subtype of the `rtt` value's static type, then we would need a more-derived Shape to assign to the allocated object header.  Since the `rtt` value is dynamic, the process of finding this more-derived Shape is dynamic to which seems suboptimal.

I think the fix, though, could just be to change the static type of the `rtt` value to match that of the allocated object, i.e.: `struct.new_rtt $t : [(rtt (ref $t)) t*] -> [(ref $t)]`.

**Comment by RossTate** [comment]
@lukewagner, I think you and I are talking about the same bug, just viewed from different perspectives. The current proposal has one argument for `rtt`. I had thought that argument was meant to represent the rtt's "guarantee", whereas what you are expressing suggests you view that argument as representing the rtt's "requirement" (in my terminology). Note that your interpretation doesn't allow for nominal-OO-style casts: if the argument to `rtt` has to match the structure exactly, then you can't use it to just ensure that an object as at least enough fields (and possibly some more). That's why I was proposing making the two separate roles of rtt's explicit.

**Comment by lukewagner** [comment]
I don't know exactly what you're referring to by "if the argument to `rtt` has to match the structure exactly", but  it sounds like you're talking about `cast`.  Have you seen how `rtt.new` allows you to create a subtype-tree of `rtt`, rooted at `rtt.anyref`, so that when you create a complete object with some `rtt` `x`, you can `cast` the resulting object not just to `x`, but any supertype ancestor of `x` in the tree?

**Comment by RossTate** [comment]
Ah, I see what you have in mind. You're making more `rtt`s than I hade in mind. Note that, with that pattern, a number of `rtt`s will be used solely for casts, solely for "inheritance", and solely for instantiation. For example, `rtt.anyref` will never be cast to and will never be instantiated, so it's sole purpose is "inheritance". However, when you make an `rtt` with `rtt.new`, the browser has no way of knowing which way you will be using it (without a larger program analysis). This is unfortunate because different uses are better implemented in different ways, so the missing "intent" forces the browser to find a common-ground implementation that can do all of these reasonably but none of these especially well.

When I try to think of the various ways that `rtt`s can be used and how these uses affect implementation, these are the various meaningful questions that come up:
1. Instantiation
   1. Can chunks be allocated with this `rtt` as its run-time type (or more generally its metadata)? If so, what structure must those chunks have?
      * This indicates whether the `rtt` should specify gc information and what the gc information is (e.g. the bitmap indicating the reference structure of the instantiation type).
   2. Can inheritors of this `rtt` have different instantiation types?
      * This can affect how the gc can pack instantiation and cast information together and into the chunk.
2. Casting
   1. Can this `rtt` be used to cast references? If so, what structure does a successful cast imply?
      * This requires the `rtt` to provide an identifier that is unique across the browser's gc space.
      * If the `rtt` can be used for both instantiation and casting, the cast type must be a supertype of the instantiation type.
      * If it's used for instantiations but not casting, then the gc can identify other similar `rtt`s and reuse them rather than create a new one.
   2. Does this `rtt` inherit from a castable `rtt`?
      * This requires the `rtt` to provide the appropriate casting table.
   3. Can inheritors of this `rtt` be used for casting?
      * If the answer to this is no, then the browser can do a lot of optimizations. For example, if there are no inheritors allowed whatsoever (so the answer to 1.2 is no as well), then casting to this `rtt` can be done just by comparing the address of this `rtt` with the one associated with the object. If the `rtt` also doesn't inherit from another castable `rtt`, then it doesn't need any casting table, making it much more compactable.
3. Structure
   1. What additional information, if any, does this `rtt` provide? (Such as a vtable.)
   2. Can inheritors provide yet more information?

Interestingly, although it's not part of the principal intent of the design, modules can do some cool things by exposing `rtt`s to other modules with a weaker type than what they were created with. For example, exposing the `rtt` for a class without its instantiation information prevents other modules from (directly) creating instances of a class. (That is, it makes the constructor private.) Similalry, exposing the `rtt` for a class with various fields missing from its casting information prevents other modules from (directly) accessing those fields. (That is, it makes those fields private.) This shouldn't really be the focus of this discussion, but I thought I should at least mention the observation.
