### ISSUE TITLE
Call for agenda for July 25 GC subgroup meeting

### ISSUE THREAD

**Issue by tlively** [WebAssembly/gc#410]
Is there anything folks want to discuss in particular at the subgroup meeting this week? If not, we can cancel it.

Potential topics include:

 1. Reinstating the rt2 <: rt1 constraint on br_on_cast, as discussed [here](https://github.com/WebAssembly/gc/issues/381#issuecomment-1644489622)
 2. Ironing out the final details of the final opcodes, as discussed [here](https://github.com/WebAssembly/gc/pull/372)
 3. The proposal to replace `sub final` with `sub open` [here](https://github.com/WebAssembly/gc/issues/333#issuecomment-1645827165)
 4. Checking in on status of spec authoring (#376)

But unless someone says otherwise, I think we can make progress asynchronously on those issues instead of meeting.

**Comment by rossberg** [comment]
I'm fine with cancelling.

**Comment by tlively** [comment]
I've gone ahead and cancelled the meeting. If everyone could take a few minutes to check in on the issues linked above tomorrow, that would be great.
