### ISSUE TITLE
why covariant array?

### ISSUE THREAD

**Issue by Guest0x0** [WebAssembly/gc#418]
https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#composite-types says:
> Array types support depth subtyping
>
>    `array <fieldtype1> <: array <fieldtype2>`
>        iff `<fieldtype1> <: <fieldtype2>`

But arrays are mutable in the proposal and should be invariant.

**Comment by vouillon** [comment]
See the next line:
 * Field types are covariant if they are immutable, invariant otherwise
