### ISSUE TITLE
Memory-Management Schemes

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/gc#42]
I've been thinking through more examples, and the more I think about it the less I like any one-size-fits-all kind of approach and the less I believe `anyref` is useful (in its current form).

For example, while the nominal approach helps keep the casting space more compact and efficient, it seems to also cause problems for languages with type constructors. For example, even if two modules of a language can make sure to use the same nominal casting type for `A` and `B`, it can be hard for them to ensure they have the same nominal casting type for `Foo(A,B)` because they may not realize the other module also needs and declares that type. Note, though, that the original proposal using structural types also doesn't address this problem, since type constructors in the high-level language may not correspond to structural types in low-level wasm, and since some types may have the same low-level representation and yet need to be kept distinct in the high-level language (e.g. C# generics).

As another example, consider algebraic data types in a Haskell- or OCaml-like language. For these, you want the meta information to indicate which case the type is. Since there are typically only a few cases, ideally this information can be picked into the same word as the meta-information used for garbage collection. It's even better if the case-tag-numbering can be dense so that one can use a jump table to efficiently jump to the appropriate case. This all is possible, but it's hard to do if the meta-information also has to enable casting to distinguish these cases between all of the arbitrary other possible cases across all the wasm modules as well as inform the garbage collector how to manage the object with no context as to what system that reference is a part of.

For these reasons among others, I think wasm should let modules declare (and import) "memory-management schemes". And rather than having a global `anyref`, we instead have `mmref <scheme>` which can refer to any reference of the designated scheme (if the scheme permits this - which not all might because it might cause problems and/or might not be useful). Instances of classes could belong to a linear-nominal kind of scheme, whereas vtables and itables could belong to cast-free kinds of schemes, and interface-method tables could belong to a flat-nominal kind of scheme. Note that structures of one scheme can contain references of other schemes. OCaml values will belong to a uniform `i31ref` scheme with AGT support. Haskell values will belong to a scheme where every value is either a collection of references or a wrapped primitive (or wrapped reference to an external scheme). And of course there's an importable scheme for DOM/JS objects.

What do y'all think?

**Comment by PoignardAzur** [comment]
Wouldn't in be extremely complicated to ensure that these schemes, which may come from untrusted or malicious sources, are memory-safe?

Whatever method you need to validate the scheme, you'll probably end up implementing some kind of internal type system anyway.

Could you give some pseudocode example of what a simple scheme would look like, and explain how the compiler would validate it?

**Comment by tlively** [comment]
Closing this as out-of-scope for the MVP, for which we have consensus on the basic structure.
