### ISSUE TITLE
Text format: inline data segments in `array.new_data`

### ISSUE THREAD

**Issue by vouillon** [WebAssembly/gc#430]
It would be nice to be able to write:
```wat
(array.new_data $string (data "Some text"))
```
and get it interpreted as:
```wat
(array.new_data $string $txt (i32.const 0) (i32.const 9))
```
with an offset 0 and a length inferred from the length of the data segment:
```wat
(data $txt "Some text")
```

And similarly with `array.new_elem` and `array.init_data/elem`.

**Comment by rossberg** [comment]
Hi @vouillon, I can see how that would be convenient, yet we do not have sugar like that for other uses of data/elem, and probably don’t want to introduce more of it. The text format is primarily meant to be a faithful rendering of Wasm code and its AST, and not optimised for hand-writing. The only instance were it supports inlining definitions into code as a shorthand is with function types, and that already creates a rather messy expansion.
