### ISSUE TITLE
Recgroup binary encoding out of date

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/gc#431]
@osa noticed that in the [rendered spec (2023-09-13 draft version)](https://webassembly.github.io/gc/core/binary/types.html#recursive-types), the binary encoding for recgroups is outdated (after #372) and inconsistent with the rest of the spec. Specifically:
- In the prose line "[Recursive types](https://webassembly.github.io/gc/core/syntax/types.html#syntax-rectype) are encoded by the byte `0x31` followed by a [vector](https://webassembly.github.io/gc/core/binary/conventions.html#binary-vec) of [sub types](https://webassembly.github.io/gc/core/syntax/types.html#syntax-subtype).", `0x31` should be `0x4E`.
- In the formal definition of `rectype`, the byte should be `0x4E` (instead of 0x4F). (See https://webassembly.github.io/gc/core/appendix/index-types.html where it is correct.)
- In the formal definition of `subtype`, the first byte of the "sub final" encoding should be `0x4F` (instead of 0x4E).

**Comment by rossberg** [comment]
Indeed, thanks! PTAL at #435.
