### ISSUE TITLE
"Illegal macro parameter reference" error in rolling and unrolling section of spec

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/gc#436]
Not sure which bit is causing the issue. Let me know what other info to supply / how I can help.

![Screenshot from 2023-09-19 06-40-11](https://github.com/WebAssembly/gc/assets/74571/97693ffe-afe9-41da-863a-7dc936999f06)

**Comment by rossberg** [comment]
That's the same problem as WebAssembly/function-references#101, where `#` anchors in xrefs conflict with Latex macro expansion using `#` to access parameters. Will try to work around it somehow.

**Comment by rossberg** [comment]
Should be fixed now.
