### ISSUE TITLE
What's the roadmap for Garbage Collection?

### ISSUE THREAD

**Issue by PoignardAzur** [WebAssembly/gc#44]
The activity for this proposal has slowed down quite a bit since August, and the current MVP implementation is full of TODOs. I'm sure work on the proposal is still ongoing, and I don't know what the priorities of the Wasm team are, but I'm really excited by the GC proposal and what it would mean for Wasm adoption.

How can we contribute? Could we get a general roadmap for what needs to be done before the GC proposal is implemented? Is there some area where the community could be helpful?

I would ordinarily look at existing repository issues for starting points, but most of the issues here seem to be inactive; mostly old questions and people proposing alternate schemes.

**Comment by chicoxyzzy** [comment]
@PoignardAzur There is [Reference Types proposal](https://github.com/WebAssembly/reference-types/blob/master/proposals/reference-types/Overview.md) which is came out of GC and Host Bindings proposals and provides a way to reference host objects inside wasm. Reference Types doesn't imply GC in wasm (GC is necessary only if host references are GC'ed) but they are the basis for GC proposal. Reference Types are on [phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#3-implementation-phase-community--working-group) of WebAssembly W3C Process.
You can track bugtrackers for status of Reference Types:
- [V8](https://bugs.chromium.org/p/v8/issues/detail?id=7581) (in progress)
- [SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1459900) (finished)

and GC:
- [V8](https://bugs.chromium.org/p/v8/issues/detail?id=7748) (in progress)
- [SpiderMonkey](https://bugzilla.mozilla.org/show_bug.cgi?id=1444925) (in progress)

Also there are some open questions in GC proposal (which is on [phase 1](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group)) like:
- for integration with JS hosts, nominal typing in JS Typed Objects vs structural typing in wasm should be solved, also nullability, etc (see https://github.com/WebAssembly/gc/pull/45)
- for all hosts [these issues](
https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#questions) should be solved

**Comment by lars-t-hansen** [comment]
@chicoxyzzy, the spidermonkey links in your post are incorrect.  Reftypes are in progress (metabugs for [milestone 1](https://bugzilla.mozilla.org/show_bug.cgi?id=1444925), [milestone 2](https://bugzilla.mozilla.org/show_bug.cgi?id=1488199)) but are absolutely not finished, nor is the reftypes spec completely finished either, there are plenty of open issues and more are coming.  The implementatiojn GC is in progress, but the link you reference above (under Reference Types) is to an initial prototype implementation of some partial ideas, and we are at least many months away from finishing this feature.

**Comment by chicoxyzzy** [comment]
@lars-t-hansen thank you for your corrections! I updated my comment

**Comment by tschneidereit** [comment]
> Typed Objects proposal for ECMAScript [is inactive and needs a huge update based on WebAssembly requirements](https://github.com/tc39/proposals/blob/master/inactive-proposals.md)

It's not really inactive, but I should update all the places to reflect that.

**Comment by chicoxyzzy** [comment]
> It's not really inactive, but I should update all the places to reflect that.

Thanks. Fixed

**Comment by PoignardAzur** [comment]
@chicoxyzzy Thank you for your answer.

Even with the information you've given here, the advancement of Wasm GC still feels somewhat vague. It woud probably be helpful to post some of this in the README or the overview.

Some questions that I still have:

- What portion of the "GC" proposal does the "Reference types" proposal cover? The GC proposal goes in some detail about what kinds of data structures references would be able to access, and how they'd access these structures. The proposal says that references should exist, but how would these references be created, written to and read from?

- What is the roadmap for Reference Types, and how can community members contribute to it? I presume a large part of the development (eg updating the Wasm compilers on each browser) will be mostly in-house for Firefox, Google and Microsoft, but are aspects of the RT proposal that could benefit from community contributions?

-  @tschneidereit What is the status of the "Typed Objects" proposal? Same questions as above, really. And how necessary are ES Typed Objects to Webasm GC, given that the GC proposal already spells out its own type system?

**Comment by PoignardAzur** [comment]
@lars-t-hansen Interesting. Correct me if I'm wrong, but is the Mozilla team currently developing the "GC" proposal independently of the progression of "Reference Types" and "Types Object", hence why you're [implementing aggregate types](https://bugzilla.mozilla.org/show_bug.cgi?id=1493712)? 

Or am I misunderstanding these links?

**Comment by lars-t-hansen** [comment]
@PoignardAzur, The reftypes proposal is not intended to require the GC proposal nor anything like typed objects for JS, and we are indeed developing reftypes semi-independently from the other proposals.  (Of course in Firefox, reftypes will be backed by a garbage collector and will be able to handle JS objects, but there are other embeddings where this is not interesting or necessary.)

**Comment by PoignardAzur** [comment]
@ lars-t-hansen That seems a little contradictory with the current [MVP specification](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md), which says its language is

> Based on reference types proposal, which introduces type anyref etc.

I think it would be a lot easier for volunteers to provide help (both in writing down specs and implementing solutions) if there was a written consensus on what is done, what is to be done, and what needs to be agreed on.

Right now it seems that the GC and Reftypes blueprints (eg spec+implem) reside in large part in the minds of Mozilla and Google engineers, which is obviously not be ideal. People can't e.g. contribute to the spec if they don't know what's the official spec and what's outdated. Same thing for contributing code.

**Comment by chicoxyzzy** [comment]
@PoignardAzur you can join WebAssembly Community Group to participate in bi-weekly CG [meetings](https://github.com/WebAssembly/meetings)

**Comment by binji** [comment]
@PoignardAzur you may want to take a look at the [notes from the most recent CG meeting at TPAC](https://github.com/WebAssembly/meetings/blob/master/2018/TPAC.md), as well as the presentations on the [reference-types](https://github.com/WebAssembly/meetings/blob/master/2018/presentations/2018-10-rossberg-reference-types.pdf) and [GC](https://github.com/WebAssembly/meetings/blob/master/2018/presentations/2018-10-rossberg-c-gc.pdf) proposals. They don't have all the spec information, but they do have the current status.

**Comment by XVilka** [comment]
Has anything changed in these two years?

**Comment by rossberg** [comment]
@XVilka, most of the work has been spent on splitting off smaller, incremental proposals as preliminaries and advancing them separately. Concretely, the [reference types](https://github.com/WebAssembly/reference-types) proposal, the [typed references](https://github.com/WebAssembly/function-references) proposal, and the [type imports](https://github.com/WebAssembly/proposal-type-imports) proposal. Unfortunately, that work is taking much longer than we anticipated.

In the meantime, some prototyping on the proposal itself [has started](https://github.com/WebAssembly/gc/issues/81).

**Comment by wisehackermonkey** [comment]
I see this as the most important feature to get mass adoption of other languages in the web!
I'm really excited to see gc languages in wasm.
