### ISSUE TITLE
Update spec text for constant instructions

### ISSUE THREAD

**Issue by wingo** [WebAssembly/gc#445]
AFAIU the intention is for e.g. `struct.new` to be a constant instruction, but the spec not does seem to include any of the text around constant expressions, yet.  So this is either a to-do or a misunderstanding on my part :)

While we are here, just another note to say that it would be nice if `array.new_data` and `array.new_elem` were constant.

**Comment by rossberg** [comment]
Oh, I thought I updated the constant expressions. Thanks for reporting!

> While we are here, just another note to say that it would be nice if array.new_data and array.new_elem were constant.

Yes, but there is a technical reason why they aren't: element and data sections appear only later in a binary, so forward-referencing them would violate declaration / streaming compilation order. There was quite a bit of discussion on one or several issues, but I can't find it right now. We hope we can eventually allow this by relaxing section order in binaries.

**Comment by tlively** [comment]
> (We hope we can eventually allow this by relaxing section order in binaries.)

Or by other means, TBD. We have not fully evaluated the trade offs among different designs for this yet, although I know @rossberg strongly favors the relaxed section order solution.

**Comment by titzer** [comment]
I implemented relaxed section order in Wizard (behind a flag of) and would also prefer relaxed section order in the future.
