### ISSUE TITLE
Validation: description of validating the `call_indirect`, `call_ref`, and `return_call_ref` instructions

### ISSUE THREAD

**Issue by q82419** [WebAssembly/gc#457]
For applying the GC proposal, the `C.types` in the validation context becomes the defined types.

As the description in [`struct.new x`](https://webassembly.github.io/gc/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-struct-mathsf-struct-new-x) for example:
 - The expansion of `C.types[x]` must be a structure type `struct fieldtype*`.

For the instructions which checking the types in `C.types` for function types, maybe have to modify to the similar description?
Take the [`call_ref x`](https://webassembly.github.io/gc/core/valid/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-call-ref-x) for example:
 - Let `[t1*] -> [t2*]` be the function type `C.types[x]`.

Maybe should be modified to:
 - The expansion of `C.types[x]` must be a function type `func [t1*] -> [t2*]`.

Thanks.

**Comment by rossberg** [comment]
Indeed, thanks! And I found a few more inconsistencies around the typing of functions, since that changed from functype to a deftype that expands to a functype. Please see #458 for a fix.

**Comment by q82419** [comment]
Close #458.
