### ISSUE TITLE
Validation: description of validating the `blocktype`

### ISSUE THREAD

**Issue by q82419** [WebAssembly/gc#459]
Hello,

Continue from #457 , the `typeidx` case of [`blocktype`](https://webassembly.github.io/gc/core/valid/types.html#block-types) will be expanded from the defined type. 

For this case, is only the `function type` expected? (That means, maybe invalid when get a `structure` or `array`?)
Thanks!

**Comment by rossberg** [comment]
Yes, this requires a function type that describes the instruction type. Other deftypes are invalid here. #460 fixes the prose to make that more explicit.
