### ISSUE TITLE
JS API: importing globals

### ISSUE THREAD

**Issue by vouillon** [WebAssembly/gc#461]
I'm wondering whether the ['read the imports' process](https://webassembly.github.io/gc/js-api/#read-the-imports) should be updated. As far as I can see, when importing a global (step 3.5), the imported value should be either a number or should implement `Global`. So, it currently does not allow to directly import a JavaScript string, for instance.

It seems that, when the global has a reference type, V8 allows to import arbitrary values as long as the type matches. Firefox is currently pickier but allows to import arbitrary values when the global has type `externref`.

**Comment by rossberg** [comment]
Good point, I agree it needs some updating to account for reference types. And corresponding tests.

@takikawa, can you look into this?

**Comment by rossberg** [comment]
Closed via #467.
