### ISSUE TITLE
Activation Frames and return arity

### ISSUE THREAD

**Issue by zapashcanon** [WebAssembly/gc#469]
Hi,

The spec [says](https://webassembly.github.io/gc/core/exec/runtime.html#activation-frames):

> Activation frames carry the return arity *n* of the respective function, hold the values of its [locals](https://webassembly.github.io/gc/core/syntax/modules.html#syntax-local) (including arguments) in the order corresponding to their static [local indices](https://webassembly.github.io/gc/core/syntax/modules.html#syntax-localidx), and a reference to the function’s own [module instance](https://webassembly.github.io/gc/core/exec/runtime.html#syntax-moduleinst):

But there's no return arity `n` in the definition, which is: `frame ::= { locals ( val ? )*, module moduleinst }`.

**Comment by rossberg** [comment]
Right, this recently got fixed [upstream](https://github.com/WebAssembly/spec/pull/1697), but I isn't merged into this fork yet.
