### ISSUE TITLE
Dimension mismatch in the premise of `array.new_data` reduction rule

### ISSUE THREAD

**Issue by jaehyun1ee** [WebAssembly/gc#476]
<img width="1381" alt="image" src="https://github.com/WebAssembly/gc/assets/44872014/58eb76a0-b7f8-4330-afc0-de52e01b5936">

I believe there is a dimension mismatch in the last premise of the above reduction rule.

The lhs, `(bytes_ft(c))^n`, is a 2d list of bytes, for 1d list of bytes, `bytes_ft(c)` is iterated by `^n`.
The rhs, `S.datas[F.module.dataaddrs[y]].data[s : n * |ft| / 8]`, on the other hand, is a 1d list of bytes.

It may be true that the lhs represents a 1d list of bytes, if we interpret `^n` as a concatenation of 1d lists.
But I do not think that it would be consistent with the other uses of `^n` throughout the entire document.

**Comment by rossberg** [comment]
Thanks, should be fixed by #479, please take a look.
