### ISSUE TITLE
Ungeneralized `global.get` instruction in constant expressions in test suite

### ISSUE THREAD

**Issue by q82419** [WebAssembly/gc#490]
Hi, according to the [PR](https://github.com/WebAssembly/function-references/commit/d1b1033a0dd11b922791f147eff229130849dd95) in function-reference proposal, the above tests are removed.

Due to depending on the function-reference proposal, maybe the tests in this GC proposal should be removed or should cause trap?

Or can you help to sync and update the test suites? Thanks!

**Comment by q82419** [comment]
The same issue occurs in [global.wast](https://github.com/WebAssembly/gc/blob/main/test/core/global.wast#L622-L645).

**Comment by rossberg** [comment]
Under the GC extensions, these tests are correct, since it relaxes the use of globals in constant expressions. But they were included in the funcref proposal by accident, which is why the PR removed them there.

**Comment by q82419** [comment]
Hi @rossberg ,

According to [module validation](https://webassembly.github.io/gc/core/valid/modules.html#valid-module), the validation of `module.globals` is as follows:

 - The sequence `module.globals` of globals must be valid with a sequence `gt*` of global types.

Which is under the context `C'` : `C'.globals` is the sequence `globals(it*)`. (The `it*` are the sequence of imported globals.)

Does it mean that under the context `C'`, the validation of globals which contains the initialization contant expressions only accepts the imported globals in the context?

Thanks!

**Comment by rossberg** [comment]
Note that the sequence of globals is not validated "in parallel" like the others (which would be by something like (C' ⊢ global : gt)*, i.e., "for each global"), but in sequence, by the [special judgement](https://webassembly.github.io/gc/core/valid/modules.html#xref-syntax-modules-syntax-global-mathit-global-ast) C' ⊢ global* : gt*, which incrementally extends C'.

**Comment by q82419** [comment]
> Note that the sequence of globals is not validated "in parallel" like the other module declarations (which would be by something like (C' ⊢ global : gt)*, i.e., "for each global"), but in sequence, by the [special judgement](https://webassembly.github.io/gc/core/valid/modules.html#xref-syntax-modules-syntax-global-mathit-global-ast) C' ⊢ global* : gt*, which incrementally extends C'.

Thanks for your information.

That is, unlike the other module declarations such as `tables` and `mems`, the validated `global type` will be appended to the `C'.globals` when validating the global sequence under the context `C'`.
Is my understanding correct?

**Comment by rossberg** [comment]
Yes. This may be generalised to other forms of declarations in the future, possibly allowing arbitrary ordering between different forms of declarations. For example, that would solve the problem that global initialisers cannot currently use array.new_data/elem instructions, because data and element segments occur _after_ globals.

**Comment by q82419** [comment]
> Yes. This may be generalised to other forms of declarations in the future, possibly allowing arbitrary ordering between different forms of declarations. For example, that would solve the problem that global initialisers cannot currently use array.new_data/elem instructions, because data and element segments occur _after_ globals.

Hi @rossberg ,

Another question is about the instantiation phase.
When in [instantiation](https://webassembly.github.io/gc/core/exec/modules.html#instantiation), the step of evaluating the `globals` are:

- 6. Let `F_init` be the auxiliary frame `{ module moduleinst_init, locals ε}`
- 7. Push the frame `F_init` to the stack.
- 8. Evaluate the `globals`. For each `global` in `module.globals`, evaluate the initializer expression `global.init`.

Which the `moduleinst_init` is the auxiliary module instance that only consists of the imported globals and the imported and allocated functions from the final module instance.
When evaluating the `global.init`, if the expression consists the `global.get` instruction, the execution will refer to the global address in current frame `F.module.globaladdr[x]`. Take the [global.wast](https://github.com/WebAssembly/gc/blob/main/test/core/global.wast#L622-L645) above for the example, even though the validation passed, this case accesses not only the imported global.
Due to the relaxing use of globals in constant expressions in validation, maybe the auxiliary frame `moduleinst_init` in instantiation should be extended too?

Thanks.

**Comment by rossberg** [comment]
Ah yes, indeed, the prose here got out of sync. The formal specification is correct: it uses the final moduleinst for evaluating constants (creating a seeming recursion, which is okay as noted by the comment below).

Please see #492 for an update to the prose.

**Comment by q82419** [comment]
Thanks for help!
