### ISSUE TITLE
`ref.{test,cast}` first time we have "one" instruction with two different opcodes?

### ISSUE THREAD

**Issue by fitzgen** [WebAssembly/gc#491]
`ref.test` is both opcode `0xFB 0x14` (for non-nullable casts) and opcode `0xFB 0x15` (for nullable casts).

`ref.cast` is both opcode `0xFB 0x16` (for non-nullable casts) and opcode `0xFB 0x17` (for nullable casts).

This is a bit funky, since we have never had this situation before AFAICT. Previously, there was a 1:1 relationship between mnemonics and opcodes, and tweaks to instructions with the same mnemonic were limited to bits in immediate bytes and things like that. When looking at a disassembly and you see a `ref.test` you don't know whether that corresponds to `0xFB 0x14` or `0xFB 0x15` until you look at the type immediate.

The funkiness comes into play when developing low-level tooling that tries to exactly reflect the binary format (eg [`wasm-encoder`](https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-encoder)). Should the `Instruction` enumeration have two variants, `RefTestNonNullable` and `RefTestNullable`, or a single variant with a `nullable: bool` field? The answer is somewhat arbitrary but also we've never been forced to make somewhat arbitrary decisions like this because there was always that 1:1 relationship between mnemonics and opcodes.

The alternatives I see are

* Move the nullability out of the opcode and into a bit on a trailing immediate byte. Not great because it increases code size.
* Split `ref.test` into `ref.test_non_nullable` and `ref.test_nullable`, each corresponding to one opcode. Same for `ref.cast`.

I'm not saying that the current state was necessarily the wrong choice -- or even if it was a mistake that it should change this late in the process -- but I am wondering if this issue was considered? (And whether we want to consider it going forward for new proposals?)

I searched through the issues but didn't find any related discussions. Apologies if I just missed it; links appreciated.

**Comment by tlively** [comment]
I do think this was something of a historical accident, in the sense that it was not a deliberate decision. During development of the proposal we wrote the immediates for these instructions out as `ref.test null? heaptype`, where we had different opcodes for `ref.test` and `ref.test null`. If you consider the `null` to be part of the mnemonic (which is questionable, but could have been easily resolved by adding an underscore), then everything would be 1:1 just as you expect. Then at some point the abstract syntax and text syntax was refactored to be `ref.test reftype`, but the binary encoding stayed the same without much discussion.

Acknowledging that nitpicking wasm-encoder's design is missing the forest for the trees, I would say that if your goal is to match the binary format as much as possible, it makes the most sense to represent null and non-null `ref.test` (and `ref.cast, respectively) as two separate instructions. If your goal is instead to match the abstract syntax as much as possible, a single instruction with a reftype field makes more sense.

**Comment by tlively** [comment]
As for what we should do when designing future proposals: I do think we want to continue having opcodes align with mnemonics 1:1 as a general principle, although I also wouldn't mind reusing this pattern where we have multiple opcodes for instructions that take reftype immediates. It's nice to save a byte in the encoding where we can.

**Comment by rossberg** [comment]
What @tlively said. If you look beyond instructions, this isn't the only place either, e.g., there are also two type opcodes for both `ref` and `sub` (not counting shorthands). And at some point having 3 or 4  opcodes for br_on_cast was on the table.

We could have kept the abstract syntax closer, but that would have been more unwieldy in explaining and specifying their meaning. It was semantically more natural to treat it as an implementation detail of the binary encoding.

That said, moving the null flag into a separate byte would have been fine as well from my perspective, since these aren't particularly frequent instructions (but would probably be severe for the `ref` type opcode).

Either way, I think that is, by far, the smallest problem we introduced with the cast instructions... ;)

**Comment by fitzgen** [comment]
Thanks for the explanations!
