### ISSUE TITLE
add ref.hash for hashcode()

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#50]
Languages like Java or .NET have a hashcode() method on every object. The value is constant for the live time of the object but must not unique for the VM. It is like a pointer in the GC managed heap.

To support such languages its sounds me a good idea to add such feature to wasm like:

`ref.hash : [anyref] -> [i32]`

My understand is that the anyref contains already this information. The alternative would be to add an extra i32 to every struct which will be a large memory overhead.

Or is there already a solution for it which I have oversee?

**Comment by rossberg** [comment]
No, anyref does not have this information. And it would be fairly expensive to implement this for every value in a stable manner -- in general an implementation would have to add an extra hidden field to every heap object, which is excessive overhead for a low-level VM.

Exposing an implementation-specific hash code would also violate Wasm's portability/non-determinism requirements. JS does not provide such a function for this very reason, even though it already sunk the cost of maintaining stable object hashes internally.

If you need hash codes you have to implement them in user space.

**Comment by titzer** [comment]
Indeed, the identity hashcode that e.g. the JVM offers for every object is both an information leak (bypasses ASLR) and an implementation overhead. I agree with @rossberg that this is better done in userspace.

**Comment by Horcrux7** [comment]
Thanks for the answer. Even if I do not like it.
