### ISSUE TITLE
In the latest standard, ref.extern is gone, but its use still exists in test.

### ISSUE THREAD

**Issue by Guo-yyds** [WebAssembly/gc#503]
In the latest standard, ref.extern is gone, but its use still exists in test.

![image](https://github.com/WebAssembly/gc/assets/75302171/5c488d67-9a03-4524-955d-9d0bff4ed855)

![image](https://github.com/WebAssembly/gc/assets/75302171/25da71da-a8ae-4d25-a9e4-25af844be784)

**Comment by rossberg** [comment]
That's easy to explain: `ref.extern` isn't (and never was) part of Wasm itself, it is part of the extended wast test scripting language, and allows emulating host references. (It should probably be renamed `ref.host` at this point.)

**Comment by q82419** [comment]
> That's easy to explain: `ref.extern` isn't (and never was) part of Wasm itself, it is part of the extended wast test scripting language, and allows emulating host references. (It should probably be renamed `ref.host` at this point.)

Same question and resolved by this explain.

**Comment by zapashcanon** [comment]
FYI here is the [description of the script language](https://github.com/WebAssembly/spec/blob/main/interpreter/README.md#scripts).
