### ISSUE TITLE
Type equivalence in modifiend spec

### ISSUE THREAD

**Issue by q82419** [WebAssembly/gc#505]
Hi,

In the type matching or closing, we may need to compare the type equivalence of 2 types, such as description in [MVP](https://github.com/WebAssembly/gc/blob/main/proposals/gc/MVP.md#equivalence).

But in the modified spec, I cannot find the type equivalence rules.

For example, in the [matching defined types](https://webassembly.github.io/gc/core/valid/matching.html#defined-types), the first rule is that the `deftype1` and `deftype2` are equal, but there's no link to the equivalence rules.
In the chapter of [rolling and unrolling](https://webassembly.github.io/gc/core/valid/conventions.html#rolling-and-unrolling), the link of [equivalence](https://webassembly.github.io/gc/core/valid/matching.html#match-deftype) is redirected to the matching defined types.

Would you help to refine this or specify the rules of type equivalence in the modified spec? Thanks!

**Comment by rossberg** [comment]
Well, there is nothing to define, this simply is plain syntactic equality. It is worth putting in a note about that, though, so I created #506.
