### ISSUE TITLE
[spec] array.init_elem: bounds check correct?

### ISSUE THREAD

**Issue by takikawa** [WebAssembly/gc#508]
The bounds check in the spec for `array.init_elem` currently has the following text with "larger than or equal to". Should it be "larger than" instead?

![image](https://github.com/WebAssembly/gc/assets/64192/b5e695d5-16d0-42dc-b59d-4fd5228ef222)

If `d` (or `s`) and `n` are both zero, then this traps if the array is empty (or the segment is).

I don't think this is the intended behavior since `array.new_elem` checks "larger than" and the tests also don't trap in this case (e.g., [this test case](https://github.com/WebAssembly/gc/blob/main/test/core/gc/array_init_elem.wast#L107)).

**Comment by rossberg** [comment]
Yes, that looks like a mistake in the prose; the same with array_init_data. The formal rules are correct. Please see #509 for a fix.
