### ISSUE TITLE
Bug-let in pick example

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/gc#51]
If I am not mistaken, there is a bug in this example:

(func $g
  (param $p1 (ref $pair)) (param $p2 (ref $pair)) (param $pick (ref $pick))
  (result (ref $C))
  (if (i31ref.get_u (cast_down i31ref (get_local $p1)))
    (then (cast_down (ref $C) (call_ref $pick (get_local $p2))))
    (else (call $new_C))
  )
)

Should this be:
(func $g
  (param $p1 (ref $pair)) (param $p2 (ref $pair)) (param $pick (ref $pick))
  (result (ref $C))
  (if (i31ref.get_u (cast_down i31ref (call_ref $pick (get_local $p1))))
    (then (cast_down (ref $C) (call_ref $pick (get_local $p2))))
    (else (call $new_C))
  )
)

??

**Comment by rossberg** [comment]
I think you are right. Fixed, thanks!
