### ISSUE TITLE
Inconsistency in validating global

### ISSUE THREAD

**Issue by ShinWonho** [WebAssembly/gc#533]
## Validation in the specification
<img width="780" alt="Screen Shot 2024-03-29 at 7 45 52 PM" src="https://github.com/WebAssembly/gc/assets/50018375/28f77651-c710-4152-b3f1-d3b7c236d2b2">

When validating globals, it uses context `C'` which only contains imported globals `igt` in the global field.

## Validation in the gc reference interpreter
```
let check_global (c : context) (glob : global) : context =
  ...
  {c with globals = c.globals @ [gtype]}

let check_list f xs (c : context) : context =
  List.fold_left f c xs

let check_module (m : module_) =
  ...
  let c =
    {empty_context with refs}
    ...
    |> check_list check_global m.it.globals
    ...
```
However, the gc reference interpreter continuously updates context and validates globals using the updated context.

## Inconsistency
I check the following wasm module with wat2wasm in wabt and the gc reference interpreter
```
;; inconsistency.wat
(module (global i32 (i32.const 0)) (global i32 (global.get 0)))
```
Because this gc proposal contains function references and tail-call proposals, I enable all of them and run wat2wasm. wat2wasm raise type error, while reference interpreter doesn't.
```
$ wabt/bin/wat2wasm --enable-function-references --enable-tail-call --enable-gc inconsistency.wat
inconsistency.wat:1:60: error: initializer expression can only reference an imported global
(module (global i32 (i32.const 0)) (global i32 (global.get 0)))
                                                           ^
$ gc/interpreter/wasm inconsistency.wat
// terminates normally
```

**Comment by rossberg** [comment]
The typing rule for modules that you quote invokes a special rule for typing _sequences_ of globals, which is defined [here](https://webassembly.github.io/gc/core/valid/modules.html#valid-globalseq) (or when you click on the turnstile). That updates the context incrementally, just like the interpreter does. This is different from iterating individual invocations as done for other entities.

So AFAICS there is no inconsistency between spec and interpreter, merely a bug in wat2wasm.
