### ISSUE TITLE
Bounds check is possible wrong on array.copy/array.fill

### ISSUE THREAD

**Issue by CharlieTap** [WebAssembly/gc#536]
Apologies I'm currently implementing this spec so I you might see few issues/questions raised from me

Both array.copy and array fill have a bounds checks  that effectively equate to:

if offset + elements_to_copy >= array.len => trap

I believe these should all be > rather than >=, I realised this when testing (because I encountered traps where I didn't expect to) and to double check I compared against table.copy/table.fill and those specifications use > rather than >=

**Comment by tlively** [comment]
Thanks for the catch! Fix at #537.
