### ISSUE TITLE
What are the possible scopes of different types?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#54]
The proposal for GC define several different types such as storagetype, functype, structtype, arraytype, reftype, etc.

And there are several scopes in WebAssembly such as locals, globals, function parameters, function returns, block returns, fields of structs, etc.

Currently the GC proposal define only for new features which type can used on which place. There is no information for the old features like locals or globals.

**Comment by rossberg** [comment]
Anything the proposal doesn't mention is not supposed to require any spec change. In particular, most of the contexts you list continue to use valtype, which in turn only changes indirectly via the extensions to reftype specified in this proposal (based on valtype being the union of numtype and reftype per the reference types proposal).

Fields of structs are specified via the new fieldtype introduced by this proposal.
