### ISSUE TITLE
How is fieldidx define on an extended type?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#56]
If I have the follow type $A and extended type $B.
```
(type $A (struct
    (field $a1 (mut i32))
    (field $a2 (mut i32))
))
(type $B (struct (extend $A)
    (field $b (mut i64))
))
```

How is the fieldidx counted in the extended type $B? If I use the follow instruction

`struct.set @B @b`

* Has $b the index 0 from type $B or the index 2 of all fields in the hierarchy?
* Can I access to an inherited field via the type $B like:

`struct.set @B @a1`
 or must I use the type of field declaration also if the instance is of type $B like:
`struct.set @A @a1`

* What occur if type $A is define in a different assembly and was imported? Is this possible?

**Comment by rossberg** [comment]
See the note in the Overview:

> (Note: the use of `extend` in this example and others is assumed to be simple syntactic sugar for expanding the referenced structure type in place; subtyping still is meant to defined structurally.)

So there is no magic here, it is just copying the field sequence into place. It's purely text format convenience, not even meant as a feature that would exist in the binary format (although it could).

**Comment by PoignardAzur** [comment]
Maybe that should be clarified in the spec?

Eg:

`(Note: the use of extend in this example and others is assumed to be simple syntactic sugar for the text format, for expanding the referenced structure type in place; subtyping is meant to be defined structurally, and there may be no 'extend' opcode in the binary format)`

**Comment by rossberg** [comment]
@PoignardAzur, done (though I wouldn't call the Overview a "spec" ;) ).

**Comment by rossberg** [comment]
@Horcrux7, you can only cast based on explicit RTTs. Those form a nominal hierarchy as produced by uses of the `rtt.new` instruction. See the section on Runtime Type in MVP.md for a bit more background explanation (the Overview admittedly got out of sync a little bit).

**Comment by Horcrux7** [comment]
> Each reference value has an associated runtime type:

Such statements in the MVP suggest the difference between rtt and struct are theoretical nature.

The problem with the MVP is that it does not define currently how subtyping or extending are declared. In the overview there are samples that I reference the overview.

Summary of the previous answers:
* fieldidx is the total index over all fields in the rtt hierarchy
* the fields in the rtt hierarchy must be duplicated in the declaration for every rtt subtype
* the WASM runtime must validate that the field declaration of the super type starts (match) the field declaration of the current type. I expect a validation exception if this is not the case.

This sounds not very intuitiv for me. But ok, I will implements it in my Java to WASM compiler.

**Comment by Horcrux7** [comment]
Thanks for the answer. This answer my questions at the moment.
