### ISSUE TITLE
Possibility of Missing Derivation Rules for the Matching Relation in Heap Types

### ISSUE THREAD

**Issue by peteryongzhong** [WebAssembly/gc#564]
In https://webassembly.github.io/gc/core/valid/matching.html#heap-types and https://github.com/WebAssembly/gc/blob/main/document/core/valid/matching.rst?plain=1#L69 

There is a rule communicated verbally that 
```
Or :math:`\heaptype_1` is a :ref:`defined type <syntax-deftype>` :math:`\deftype_1` and :math:`\heaptype_2` is a :ref:`defined type <syntax-deftype>` :math:`\deftype_2`, and :math:`\deftype_1` :ref:`matches <match-deftype>` :math:`\deftype_2`.
```

However, and perhaps I am mistaken here completely, it does not appear that it is reflected in the inference rules rendered.

**Comment by rossberg** [comment]
Yes, I left this out intentionally, since it would have identical looking premise and conclusion. While technically different relations, that might be more confusing than helpful to many readers, so this injection is assumed to be implicit.

**Comment by peteryongzhong** [comment]
I see thanks for this explanation.
