### ISSUE TITLE
Confusion about a potentially flipped Matching Relation for Indirect Call

### ISSUE THREAD

**Issue by peteryongzhong** [WebAssembly/gc#569]
In https://github.com/WebAssembly/gc/blob/main/document/core/exec/instructions.rst?plain=1#L4371 

I am wondering why it is the case that the type declared on `call_indirect` is more refined than the type from the function actually retrieved from the table? I might be missing something, but intuitively it feels like it should be the other way around. 

<img width="810" alt="image" src="https://github.com/user-attachments/assets/f64eeb12-b61a-4b5b-a9ba-509689e353d8">

https://webassembly.github.io/gc/core/exec/instructions.html#xref-syntax-instructions-syntax-instr-control-mathsf-call-indirect-x-y

**Comment by tlively** [comment]
Yep, that looks flipped to me. @rossberg, do you agree?

**Comment by rossberg** [comment]
Indeed, thanks for spotting! Should be fixed now.
