### ISSUE TITLE
Consider splitting out typed function pointers

### ISSUE THREAD

**Issue by aykevl** [WebAssembly/gc#60]
Reading through the overview, I saw that there is a proposal for typed function pointers.

Is there anything that typed function pointers provide that is not already covered by `anyfunc`? I have a feeling that the part of the spec that describes typed function pointers is leaning a bit too much towards supporting the full Java type system. While I think that typed function pointers can be very useful for performance reasons, I don't see how they are related to GC except for making the type system even more complex. Falling back to `anyfunc` (with a small performance hit) and simply requiring the language to perform its own language-dependent downcasts if needed seems like a simpler solution right now.

Possibly related: #32

**Comment by titzer** [comment]
AFAICT, there are no downcasts from `anyfunc` at the moment. What would they downcast to, if there are no typed function pointers? Or do you propose to write any `anyfunc` into a table and then do a `call_indirect` on it? That is pretty slow.

**Comment by rossberg** [comment]
I actually just proposed splitting out typed function references from the GC proposal at last weeks CG meeting. See [this branch](https://github.com/WebAssembly/gc/blob/funcref/proposals/gc/Funcref.md) for a tentative sketch of such a standalone proposal.

**Comment by aykevl** [comment]
> Or do you propose to write any `anyfunc` into a table and then do a `call_indirect` on it? That is pretty slow.

That's what I would propose, yes. Yes, it will be slow. But similar to interior pointers in #59, I don't think this should be part of a MVP. (And if this is part of the MVP, why not interior pointers?)

> I actually just proposed splitting out typed function references from the GC proposal at last weeks CG meeting.

Great! And good to hear there is ongoing work!

**Comment by binji** [comment]
Typed function references has been moved to its own repo, here: https://github.com/webassembly/function-references. Closing.
