### ISSUE TITLE
Arrays are references?

### ISSUE THREAD

**Issue by fgmccabe** [WebAssembly/gc#61]
This is a question more than an issue: in this proposal, are arrays reference types?

If so, does this mean that you cannot have an array as an embedded part of another structure?

Also, it does not seem clear from the proposal whether array.get/set is bounds checked. If not, then this is a security hole.

**Comment by rossberg** [comment]
Yes, arrays are available only as references in the MVP. The ability to nest aggregates is described as a post-MVP extension, see the section on Nesting in the overview. For the MVP you'll need an indirection to encode "array objects".

I added text specifying the traps for out-of-bounds array accesses.
