### ISSUE TITLE
Please provide some way to create encapsulated closures

### ISSUE THREAD

**Issue by erights** [WebAssembly/gc#7]
It says that a closure is a pair of code and state. Is this pair separable? For code given just the pair, can it access the state other than by invoking that closure's code on that state?

If the answer is yes, then could we have encapsulating closures, i.e., invocable inseparable pairs of code and state?

**Comment by rossberg-chromium** [comment]
The bare encoding given in the overview could be encapsulated if we introduced abstract types. If made abstract, the type of each closure environment would not be known to other modules, and would thus be entirely opaque. Without that, the encoding would not be encapsulated.

FWIW, the same applies to the usual representation of objects.

For closures, another option would be to introduce closures as a primitive notion, as briefly hinted at in the overview.

**Comment by erights** [comment]
Thanks. I now understand the answer to my question, and so have renamed this issue into a feature request.

**Comment by tlively** [comment]
I believe this is the goal of the `func.bind` instruction mentioned in the [typed function references](https://github.com/WebAssembly/function-references) proposal. I'll close this old issue in favor of continued discussion on that repo.

**Comment by rossberg** [comment]
As a side note: I think we more or less converged on dropping func.bind from the function references proposal. I plan to remove it there and move it to the Post-MVP doc here.
