### ISSUE TITLE
Is Webassembly supporting arrays?

### ISSUE THREAD

**Issue by AchalaSB** [WebAssembly/gc#79]
Hi,

If I write code in Rust which uses Array can I compile it to wasm? (without wasm-bindgen crate).
Then can I use this wasm binary further?

Thanks

**Comment by binji** [comment]
This question is probably better to ask in a Rust support forum. But yes, Rust supports Arrays via linear memory. AFAIK they are unlikely to use the gc proposal for this. Closing.

**Comment by tschneidereit** [comment]
Indeed, this was discussed quite extensively, with the conclusion that directly operating on GC-managed Arays (or other types of values) in Rust would require significant changes to the compiler, including LLVM, and the language.
