### ISSUE TITLE
Can references be passed between wasm worlds?

### ISSUE THREAD

**Issue by erights** [WebAssembly/gc#8]
I no longer remember the right terminology for the large-scale wasm unit that is effectively an instance of the vm, where multiple such instances can exist within a JS heap. ("wasm vm"?)

I remember the paper making a big deal of the fact that only data can be passed between these wasm worlds. In WebAssembly-gc can references be passed as well? If closure encapsulation is directly implemented as indivisible pairs, (See #7 ), can these be passed between wasm worlds?

**Comment by rossberg-chromium** [comment]
I don't think we have a specific term for the execution engine, but Wasm VM sounds fine.

Yes, reference types -- including potential primitive closure types, which would also be reference types -- can be used for function parameter/results and globals, and references thus be passed to the outside world, including other Wasm modules. Likewise, foreign references could be passed into Wasm, including ones from the embedder (see the section on Host Types).

**Comment by jfbastien** [comment]
`postMessage` to another JS VM?

**Comment by rossberg-chromium** [comment]
I hope that's not a feature request. ;) Because I don't think so. I can't see how cloning could sanely be automatised. And we certainly don't want remote references or distributed GC. It would be faithful to the low-level nature of Wasm that you have to program the necessary serialisation yourself.

**Comment by jfbastien** [comment]
Haha, no. I was asking for a clarification.

**Comment by lukewagner** [comment]
Ideally, I think, there is no need for a distinct notion of "wasm vm" but rather we would reuse/generalize existing JS concepts like agent, agent cluster, etc.  That way the way in which two wasm instances share GC references is not fundamentally different than the way wasm and JS share GC references.

**Comment by tlively** [comment]
Closing this issue because the original question has been answered. Feel free to reopen for further discussion.
