### ISSUE TITLE
Creating a GC subgroup

### ISSUE THREAD

**Issue by binji** [WebAssembly/gc#80]
Given that the meeting to discuss creating a GC subgroup has been postponed a few times now (most recently [here](https://github.com/WebAssembly/meetings/pull/520)), we should probably try to have the discussion asynchronously on a GitHub issue.

The primary things we should do:

* Plan a time and cadence for regular meetings (see, for example, the [simd](https://github.com/WebAssembly/simd/issues/202) and [interface type](https://github.com/WebAssembly/interface-types/issues/81) meetings). Every two weeks seems like a good default, but feel free to decide as a subgroup
* Create a charter (see for example the [WASI charter](https://github.com/WebAssembly/WASI/blob/master/Charter.md))

**Comment by fgmccabe** [comment]
I agree.
However, it would be good to float a charter -- to focus the discussion.

**Comment by lars-t-hansen** [comment]
Indeed.  We have people interested in the full reftypes+objects GC proposal but also in linear-memory GC assists (I'm in both factions) and we should at least figure out if we're going to discuss both those things or only the former.

**Comment by kripken** [comment]
I'm also in both factions (native GC objects and linear-memory GC assisting). If we think it's too much space to cover in a specific subgroup, perhaps two separate subgroups? However, I think given the overlap that might be less efficient.

**Comment by rossberg** [comment]
I tried drafting a charter in #82, stealing properly from the WASI charter. Comments welcome.

**Comment by aardappel** [comment]
+1 for both factions ;)

**Comment by binji** [comment]
We've agreed in the community group to have the subgroup meet, so let's plan for a first meeting in the next month. It seems like generally our groups prefer meetings starting in the range 8am-10am PT (5pm-7pm CET), so I'll assume the same here.

Please fill out this form with your preferences: https://forms.gle/ukXFhz4t3mtMhCG78

**Comment by GergelyBuday** [comment]
I am interested. What should I read that was done on GC previously?

**Comment by binji** [comment]
The best resource to start are the overviews:

From this repo:
https://github.com/WebAssembly/gc/blob/master/proposals/gc/Overview.md
https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md

And a second proposal in a forked repo:
https://github.com/soil-initiative/gc/pull/1
https://github.com/soil-initiative/gc/pull/2

And discussion about a linear-memory GC here:
https://github.com/WebAssembly/gc/issues/78

And finally some discussion on stack-walking to implement a GC here:
https://github.com/WebAssembly/design/issues/1340

**Comment by binji** [comment]
Thank you to everyone who filled out the form. The times that worked for most people are:
- Monday, May 18, 9am PDT (5pm CET) **16 votes**
- Tuesday, May 19, 9am PDT (5pm CET) **16 votes**
- Friday, May 29, 9am PDT (5pm CET) **15 votes**

My apologies for not posting this sooner, as the Monday time has already past, and tomorrow's meeting is probably too soon for an agenda.

Given that, I suggest we have our first meeting **Tuesday, June 2nd, 9am PDT (5pm CET)**. This meeting time uses the same slot as the larger community group meeting, but on the odd week. Most of the group (60%) said they'd prefer a two week cadence, which works well here too.

**Comment by binji** [comment]
I've added an issue to collect agenda items for the first meeting: https://github.com/WebAssembly/gc/issues/89.

**Comment by lars-t-hansen** [comment]
9am PDT is 6pm CET at the moment (and on that day).

**Comment by kmiller68** [comment]
Is there going to be a calendar invite with the, presumably, zoom details? I didn't add my email to the list until today so it could be I missed the email blast.

**Comment by binji** [comment]
@lars-t-hansen oops, thanks.
@kmiller68 Yep, I'll set up the calendar event and zoom details this week. I haven't sent anything out yet.

**Comment by binji** [comment]
We now have a charter and a first meeting scheduled, closing this issue.
