### ISSUE TITLE
Missing use case for rtt.sub

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/gc#83]
The overview states the following when introducing `rtt.sub`.

> More generally, runtime type checks can verify a subtype relation between runtime types. In order to make these checks cheap, runtime subtyping follows a nominal semantics.

However, `rtt.sub` is not used anywhere in the overview; everything just uses `rtt.get` and then casts to the result. In which case, why does the MVP provide `rtt` at all, or why do the examples in the overview not use the more efficient `rtt.sub`?

Please update the overview or the MVP so that we can all be on the same page as to how these features are expected to be used.

**Comment by tlively** [comment]
Closing this because `rtt.sub` has been removed from the proposal. For the latest discussion of RTTs, see #275.
