### ISSUE TITLE
copy / clone

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#92]
Will there be an option to create a clone (shallow copy) of any GC object?

It can be very difficult to implement such generic feature in a function that work for every object. Currently I does not have any idea how this should be possible. If it is possible then it will be have a large performance overhead.

In the native code it should be very simple to do it.

An alternative would be an override of one object with the content of another. Then a clone would be a new + override.

**Comment by tlively** [comment]
No, there is no plan to offer this functionality built into the language. Since Wasm is meant to be a compilation target, generating functions to copy any particular type of GC object can be left to the compiler.
