### ISSUE TITLE
Which kind is needed for ref.null and ref.is_null for a struct type?

### ISSUE THREAD

**Issue by Horcrux7** [WebAssembly/gc#93]
I try to define a global of a struct type.  On the definition I need a initial value. This is typical a null value. After the last changes this required a kind. I try the follows without luck. Which kind should be valid ref.null in this case?

```wasm
(module
  (type $foobar (struct
    (field $a (mut i32))
  ))
  (global $valGlobal (mut (optref $foobar))ref.null extern)
)
```
--> type mismatch: initializer type and expected type don't match

```wasm
(module
  (type $foobar (struct
    (field $a (mut i32))
  ))
  (global $valGlobal (mut (optref $foobar))ref.null (optref $foobar))
)
```
--> bad type

**Comment by binji** [comment]
Which implementation are you testing this on? It may be better to open a bug there.

**Comment by rossberg** [comment]
For a typed reference, the right type (following what's in the typed-func-ref proposal) would be
```
(ref.null (type $foobar))
```

**Comment by Horcrux7** [comment]
@binji 
> Which implementation are you testing this on?
With SpiderMonkey nightly.
> It may be better to open a bug there.
Before I can open it I need to know what are the right syntax.
